import type {
  Base64Alphabet,
  Base64Decoded,
  Base64FileAnswer,
  Base64Options,
  Base64Problem,
  Base64Saved,
  CaseConversion,
  CodecDirection,
  EndingCounts,
  FileProblem,
  FinalNewline,
  FinalNewlineChange,
  LineBreaksAnswer,
  LineBreaksRequest,
  LineEnding,
  QueryParameter,
  SlugRequest,
  SlugSeparator,
  TextCase,
  UrlAnswer,
  UrlCodecAnswer,
  UrlCodecRequest,
  UrlParts,
  UrlProblem,
  UrlScope,
} from '@core/ipc/bindings';

/** What the tools ask Rust and what it answers, as it crosses: no date, nothing to convert. */
export type {
  Base64Alphabet,
  Base64Decoded,
  Base64FileAnswer,
  Base64Options,
  Base64Problem,
  Base64Saved,
  CaseConversion,
  CodecDirection,
  EndingCounts,
  FileProblem,
  FinalNewline,
  FinalNewlineChange,
  LineBreaksAnswer,
  LineBreaksRequest,
  LineEnding,
  QueryParameter,
  SlugRequest,
  SlugSeparator,
  TextCase,
  UrlAnswer,
  UrlCodecAnswer,
  UrlCodecRequest,
  UrlParts,
  UrlProblem,
  UrlScope,
};
