import { ToolDefinition } from '@core/services/tools/tool.model';

/**
 * Every tool, in its panel's order, each in a folder beside this one. Adding one is an entry
 * here: its name and its line are read from its id, and its component is a chunk of its own,
 * loaded the first time it is opened.
 */
export const TOOLS: readonly ToolDefinition[] = [
  {
    id: 'case',
    category: 'text',
    keywords: [
      'camelCase',
      'PascalCase',
      'snake_case',
      'kebab-case',
      'CONSTANT_CASE',
      'dot.case',
      'path/case',
      'Train-Case',
      'lowercase',
      'UPPERCASE',
      'flatcase',
      'slug',
      'permalink',
      'ascii',
    ],
    load: () => import('./case/case-tool.component').then((m) => m.CaseToolComponent),
  },
  {
    id: 'line-breaks',
    category: 'text',
    keywords: ['crlf', 'lf', 'eol', 'newline', 'whitespace'],
    load: () => import('./line-breaks/line-breaks-tool.component').then((m) => m.LineBreaksToolComponent),
  },
  {
    id: 'text-stats',
    category: 'text',
    keywords: [
      'count',
      'characters',
      'words',
      'lines',
      'length',
      'frequency',
      'compter',
      'caractères',
      'mots',
    ],
    load: () => import('./text-stats/text-stats-tool.component').then((m) => m.TextStatsToolComponent),
  },
  {
    id: 'diff',
    category: 'text',
    keywords: ['diff', 'compare', 'patch', 'diff -u', 'unified', 'json', 'rfc 6902'],
    load: () => import('./diff/diff-tool.component').then((m) => m.DiffToolComponent),
  },
  {
    id: 'hash',
    category: 'crypto',
    keywords: ['md5', 'sha1', 'sha256', 'sha512', 'sha3', 'hmac', 'digest', 'checksum', 'webhook'],
    load: () => import('./hash/hash-tool.component').then((m) => m.HashToolComponent),
  },
  {
    id: 'password',
    category: 'crypto',
    keywords: ['password', 'passphrase', 'secret', 'random', 'entropy'],
    load: () => import('./password/password-tool.component').then((m) => m.PasswordToolComponent),
  },
  {
    id: 'identifiers',
    category: 'crypto',
    keywords: [
      'uuid',
      'guid',
      'v4',
      'v7',
      'ulid',
      'nanoid',
      'cuid',
      'objectid',
      'mongodb',
      'ksuid',
      'identifier',
    ],
    load: () => import('./identifiers/identifiers-tool.component').then((m) => m.IdentifiersToolComponent),
  },
  {
    id: 'jwt',
    category: 'crypto',
    keywords: ['jwt', 'json web token', 'bearer', 'hs256', 'claims', 'exp', 'token'],
    load: () => import('./jwt/jwt-tool.component').then((m) => m.JwtToolComponent),
  },
  {
    id: 'url-codec',
    category: 'encode',
    keywords: ['url', 'uri', 'query', 'querystring', 'percent', 'encodeURIComponent', 'escape', 'parse'],
    load: () => import('./url-codec/url-codec-tool.component').then((m) => m.UrlCodecToolComponent),
  },
  {
    id: 'base64',
    category: 'encode',
    keywords: [
      'base64',
      'b64',
      'base32',
      'hex',
      'hexadecimal',
      'binary',
      'binaire',
      'bytes',
      'jwt',
      'data uri',
    ],
    load: () => import('./base64/base64-tool.component').then((m) => m.Base64ToolComponent),
  },
  {
    id: 'convert',
    category: 'encode',
    keywords: ['json', 'toml', 'xml', 'yaml', 'yml', 'convert'],
    load: () => import('./convert/convert-tool.component').then((m) => m.ConvertToolComponent),
  },
  {
    id: 'colour',
    category: 'encode',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'oklch', 'contrast', 'wcag'],
    load: () => import('./colour/colour-tool.component').then((m) => m.ColourToolComponent),
  },
  {
    id: 'json-generator',
    category: 'generate',
    keywords: ['json', 'schema', 'mock', 'fixture', 'fake', 'faker'],
    load: () =>
      import('./json-generator/json-generator-tool.component').then((m) => m.JsonGeneratorToolComponent),
  },
  {
    id: 'lorem',
    category: 'generate',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text'],
    load: () => import('./lorem/lorem-tool.component').then((m) => m.LoremToolComponent),
  },
  {
    id: 'qr',
    category: 'generate',
    keywords: ['qr', 'qr code', 'qrcode', 'wifi', 'vcard', 'mailto', 'svg', 'png', 'barcode'],
    load: () => import('./qr/qr-tool.component').then((m) => m.QrToolComponent),
  },
  {
    id: 'dates',
    category: 'time',
    keywords: ['timestamp', 'unix', 'epoch', 'iso 8601', 'rfc 3339', 'rfc 2822', 'date', 'now'],
    load: () => import('./dates/dates-tool.component').then((m) => m.DatesToolComponent),
  },
  {
    id: 'zones',
    category: 'time',
    keywords: ['timezone', 'time zone', 'tz', 'iana', 'utc', 'gmt', 'dst', 'offset'],
    load: () => import('./zones/zones-tool.component').then((m) => m.ZonesToolComponent),
  },
  {
    id: 'cron',
    category: 'time',
    keywords: ['cron', 'crontab', 'schedule', 'quartz', '@daily', 'job'],
    load: () => import('./cron/cron-tool.component').then((m) => m.CronToolComponent),
  },
  {
    id: 'sizes',
    category: 'calc',
    keywords: ['byte', 'octet', 'kb', 'mb', 'gb', 'kib', 'mib', 'gib', 'bit', 'mbit', 'size'],
    load: () => import('./sizes/sizes-tool.component').then((m) => m.SizesToolComponent),
  },
  {
    id: 'percentages',
    category: 'calc',
    keywords: ['percent', 'percentage', '%', 'pourcent', 'ratio', 'discount', 'vat', 'tva'],
    load: () => import('./percentages/percentages-tool.component').then((m) => m.PercentagesToolComponent),
  },
  {
    id: 'permissions',
    category: 'calc',
    keywords: ['chmod', 'umask', 'rwx', 'octal', 'setuid', 'setgid', 'sticky', 'ls -l'],
    load: () => import('./permissions/permissions-tool.component').then((m) => m.PermissionsToolComponent),
  },
  {
    id: 'checks',
    category: 'calc',
    keywords: ['luhn', 'iban', 'mod 97', 'credit card', 'carte', 'checksum', 'bic', 'visa', 'mastercard'],
    load: () => import('./checks/checks-tool.component').then((m) => m.ChecksToolComponent),
  },
  {
    id: 'cidr',
    category: 'calc',
    keywords: [
      'cidr',
      'subnet',
      'sous-réseau',
      'netmask',
      'masque',
      'ipv4',
      'ipv6',
      'ip',
      'rfc 1918',
      'broadcast',
    ],
    load: () => import('./cidr/cidr-tool.component').then((m) => m.CidrToolComponent),
  },
  {
    id: 'http-status',
    category: 'reference',
    keywords: ['http', 'status', 'statut', 'code', 'rfc 9110', '404', '500', 'redirect', 'nginx'],
    load: () => import('./http-status/http-status-tool.component').then((m) => m.HttpStatusToolComponent),
  },
  {
    id: 'http-headers',
    category: 'reference',
    keywords: ['header', 'en-tête', 'cors', 'csp', 'hsts', 'cookie', 'cache-control', 'content-type'],
    load: () => import('./http-headers/http-headers-tool.component').then((m) => m.HttpHeadersToolComponent),
  },
  {
    id: 'mime-types',
    category: 'reference',
    keywords: ['mime', 'media type', 'content-type', 'extension', 'json', 'png', 'pdf'],
    load: () => import('./mime-types/mime-types-tool.component').then((m) => m.MimeTypesToolComponent),
  },
  {
    id: 'ports',
    category: 'reference',
    keywords: ['port', 'tcp', 'udp', 'iana', 'ssh', 'postgresql', 'redis', 'firewall', 'pare-feu'],
    load: () => import('./ports/ports-tool.component').then((m) => m.PortsToolComponent),
  },
  {
    id: 'signals',
    category: 'reference',
    keywords: ['signal', 'kill', 'sigterm', 'sigkill', 'sighup', 'sigint', 'posix', 'trap'],
    load: () => import('./signals/signals-tool.component').then((m) => m.SignalsToolComponent),
  },
  {
    id: 'ascii',
    category: 'reference',
    keywords: ['ascii', 'character', 'caractère', 'code', 'hex', 'control', 'newline', 'escape'],
    load: () => import('./ascii/ascii-tool.component').then((m) => m.AsciiToolComponent),
  },
  {
    id: 'regex-sheet',
    category: 'reference',
    keywords: ['regex', 'regexp', 'expression régulière', 'pcre', 'lookbehind', 'lookahead', 'cheat sheet'],
    load: () => import('./regex-sheet/regex-sheet-tool.component').then((m) => m.RegexSheetToolComponent),
  },
  {
    id: 'markdown-sheet',
    category: 'reference',
    keywords: ['markdown', 'md', 'gfm', 'commonmark', 'readme', 'cheat sheet'],
    load: () =>
      import('./markdown-sheet/markdown-sheet-tool.component').then((m) => m.MarkdownSheetToolComponent),
  },
  {
    id: 'mustache-sheet',
    category: 'reference',
    keywords: ['mustache', 'handlebars', 'template', 'gabarit', '{{', 'partial', 'cheat sheet'],
    load: () =>
      import('./mustache-sheet/mustache-sheet-tool.component').then((m) => m.MustacheSheetToolComponent),
  },
];
