// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  No command returns the raw list: it would invite re-filtering on the front end. */
	queryNotes: (query: NotesQuery) => typedError<NotesView, AppError>(__TAURI_INVOKE("query_notes", { query })),
	/**
	 *  The whole note. A list sends previews ([`DisplayNote::truncated`]), so the editor and
	 *  every copy of a long body read it here.
	 */
	getNote: (id: string) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("get_note", { id })),
	createNote: (draft: NoteDraft) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("create_note", { draft })),
	/**
	 *  A copy to start another note from, attachments included and history left behind. The
	 *  title is the front end's: its suffix is a translation.
	 */
	duplicateNote: (id: string, title: string) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("duplicate_note", { id, title })),
	/**
	 *  What a paste into an empty Note is. Asked by the front end before it writes: typing keeps
	 *  a Note prose, and only a paste of code turns it into a snippet with a language.
	 */
	detectLanguage: (content: string) => __TAURI_INVOKE<Language>("detect_language", { content }),
	/**  No lock, but off the window's thread: a document of a few megabytes takes a while. */
	exploreJson: (query: JsonQuery) => typedError<JsonView, AppError>(__TAURI_INVOKE("explore_json", { query })),
	convertCase: (request: CaseRequest) => typedError<CaseAnswer, AppError>(__TAURI_INVOKE("convert_case", { request })),
	fixLineBreaks: (request: LineBreaksRequest) => typedError<LineBreaksAnswer, AppError>(__TAURI_INVOKE("fix_line_breaks", { request })),
	parseUrl: (text: string) => typedError<UrlAnswer, AppError>(__TAURI_INVOKE("parse_url", { text })),
	urlCodec: (request: UrlCodecRequest) => typedError<UrlCodecAnswer, AppError>(__TAURI_INVOKE("url_codec", { request })),
	encodeBytes: (request: EncodeRequest) => typedError<Encodings, AppError>(__TAURI_INVOKE("encode_bytes", { request })),
	/**  By its path: the bytes are read here and never cross the bridge. */
	encodeBase64File: (path: string) => typedError<Base64FileAnswer, AppError>(__TAURI_INVOKE("encode_base64_file", { path })),
	decodeBytes: (request: DecodeRequest) => typedError<DecodeAnswer, AppError>(__TAURI_INVOKE("decode_bytes", { request })),
	saveBytes: (request: DecodeRequest, path: string) => typedError<SavedBytes, AppError>(__TAURI_INVOKE("save_bytes", { request, path })),
	hashInput: (request: HashRequest) => typedError<HashAnswer, AppError>(__TAURI_INVOKE("hash_input", { request })),
	/**  No randomness from the system is the unexpected: nothing weaker is drawn in its place. */
	generatePasswords: (request: PasswordRequest) => typedError<PasswordAnswer, AppError>(__TAURI_INVOKE("generate_passwords", { request })),
	generateIdentifiers: (request: IdentifiersRequest) => typedError<string[], AppError>(__TAURI_INVOKE("generate_identifiers", { request })),
	inspectIdentifier: (text: string) => typedError<IdInspection, AppError>(__TAURI_INVOKE("inspect_identifier", { text })),
	textStats: (request: StatsRequest) => typedError<TextStats, AppError>(__TAURI_INVOKE("text_stats", { request })),
	describeQrCode: (request: QrRequest) => typedError<QrAnswer, AppError>(__TAURI_INVOKE("describe_qr_code", { request })),
	saveQrCode: (request: QrRequest, format: QrFormat, path: string) => typedError<SavedCode, AppError>(__TAURI_INVOKE("save_qr_code", { request, format, path })),
	/**  The image is written natively: its pixels never cross the bridge. `false` when there is no code. */
	copyQrCode: (request: QrRequest) => typedError<boolean, AppError>(__TAURI_INVOKE("copy_qr_code", { request })),
	describeCidr: (request: CidrRequest) => typedError<CidrAnswer, AppError>(__TAURI_INVOKE("describe_cidr", { request })),
	describeColour: (request: ColourRequest) => typedError<ColourAnswer, AppError>(__TAURI_INVOKE("describe_colour", { request })),
	convertData: (request: ConvertRequest) => typedError<ConvertAnswer, AppError>(__TAURI_INVOKE("convert_data", { request })),
	generateJson: (request: GenerateRequest) => typedError<GenerateAnswer, AppError>(__TAURI_INVOKE("generate_json", { request })),
	loremIpsum: (request: LoremRequest) => typedError<LoremAnswer, AppError>(__TAURI_INVOKE("lorem_ipsum", { request })),
	diffJson: (request: JsonDiffRequest) => typedError<JsonDiffAnswer, AppError>(__TAURI_INVOKE("diff_json", { request })),
	diffText: (request: TextDiffRequest) => typedError<TextDiffAnswer, AppError>(__TAURI_INVOKE("diff_text", { request })),
	/**  A date written without an offset is read in the machine's zone, as the person typing it means. */
	describeInstant: (request: InstantRequest) => typedError<InstantAnswer, AppError>(__TAURI_INVOKE("describe_instant", { request })),
	currentInstant: () => typedError<string, AppError>(__TAURI_INVOKE("current_instant")),
	/**  The two dates are read in the machine's zone, which the answer names. */
	measureDurations: (request: DurationsRequest) => typedError<DurationsAnswer, AppError>(__TAURI_INVOKE("measure_durations", { request })),
	searchTimeZones: (query: string) => typedError<ZoneEntry[], AppError>(__TAURI_INVOKE("search_time_zones", { query })),
	placeInZones: (request: ZonesRequest) => typedError<ZonesAnswer, AppError>(__TAURI_INVOKE("place_in_zones", { request })),
	timeInZone: (zone: string | null) => typedError<string, AppError>(__TAURI_INVOKE("time_in_zone", { zone })),
	describeCron: (request: CronRequest) => typedError<CronAnswer, AppError>(__TAURI_INVOKE("describe_cron", { request })),
	convertSize: (request: SizesRequest) => typedError<SizesAnswer, AppError>(__TAURI_INVOKE("convert_size", { request })),
	estimateTransfer: (request: TransferRequest) => typedError<TransferAnswer, AppError>(__TAURI_INVOKE("estimate_transfer", { request })),
	answerPercentages: (request: PercentagesRequest) => typedError<PercentagesAnswer, AppError>(__TAURI_INVOKE("answer_percentages", { request })),
	describePermissions: (request: PermissionsRequest) => typedError<PermissionsAnswer, AppError>(__TAURI_INVOKE("describe_permissions", { request })),
	checkDigits: (request: CheckRequest) => typedError<CheckAnswer, AppError>(__TAURI_INVOKE("check_digits", { request })),
	/**  The token and the secret are zeroed once the answer is made. */
	decodeJwt: (request: JwtRequest) => typedError<JwtAnswer, AppError>(__TAURI_INVOKE("decode_jwt", { request })),
	/**
	 *  The first launch: the space, its folders and the notes in one transaction, since a space
	 *  standing alone reads as "already seeded" for good. The strings stay on the front end, with
	 *  the translations. Answers the space it made, which the front end opens on.
	 */
	seedSamples: (spaceName: string, folders: string[], notes: SampleNote[]) => typedError<Space, AppError>(__TAURI_INVOKE("seed_samples", { spaceName, folders, notes })),
	updateNote: (id: string, patch: NotePatch) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("update_note", { id, patch })),
	/**
	 *  The bodies kept beside a note, newest first.
	 * 
	 *  Instants and sizes, never the bodies.
	 */
	listRevisions: (id: string) => typedError<Revision[], AppError>(__TAURI_INVOKE("list_revisions", { id })),
	/**  What going back to a kept body would change, line by line, against the current text. */
	revisionDiff: (id: string, revisionId: string) => typedError<DiffLine[], AppError>(__TAURI_INVOKE("revision_diff", { id, revisionId })),
	/**
	 *  Goes back to a kept body, dropping it and every body kept after it from the history.
	 * 
	 *  Leaves `updated_at` alone: putting something back is not editing it.
	 */
	restoreRevision: (id: string, revisionId: string) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("restore_revision", { id, revisionId })),
	/**
	 *  Moves to the trash: the note comes back through [`restore_notes`] for
	 *  [`trash::RETENTION`].
	 */
	deleteNote: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note", { id })),
	deleteNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_notes", { ids })),
	restoreNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("restore_notes", { ids })),
	/**  Purges first: the trash must never show a note a restart would erase. */
	listTrash: () => typedError<TrashedNote[], AppError>(__TAURI_INVOKE("list_trash")),
	purgeNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("purge_notes", { ids })),
	emptyTrash: () => typedError<number, AppError>(__TAURI_INVOKE("empty_trash")),
	moveNotes: (ids: string[], spaceId: string) => typedError<NotePlacement[], AppError>(__TAURI_INVOKE("move_notes", { ids, spaceId })),
	/**  The undo of [`move_notes`]: each note goes back to the space it left. */
	moveNotesBack: (placements: NotePlacement[]) => typedError<number, AppError>(__TAURI_INVOKE("move_notes_back", { placements })),
	/**  Normalized here as everywhere else, or a typed `#urgent` would not join `urgent`. */
	tagNotes: (ids: string[], tags: string[]) => typedError<NoteTag[], AppError>(__TAURI_INVOKE("tag_notes", { ids, tags })),
	/**  The undo of [`tag_notes`]: exactly the pairs it added, and nothing wider. */
	untagNotes: (pairs: NoteTag[]) => typedError<number, AppError>(__TAURI_INVOKE("untag_notes", { pairs })),
	/**  Answers each note whose priority moved, with the one it had; `updated_at` stays. */
	setPriority: (ids: string[], priority: Priority) => typedError<NotePriority[], AppError>(__TAURI_INVOKE("set_priority", { ids, priority })),
	/**  The undo of [`set_priority`]: each note gets back the priority it had. */
	restorePriorities: (previous: NotePriority[]) => typedError<number, AppError>(__TAURI_INVOKE("restore_priorities", { previous })),
	/**  What a corpus-wide tag action is about to touch, asked before it runs. */
	countNotesTagged: (tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("count_notes_tagged", { tags })),
	listTags: () => typedError<TagUsage[], AppError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Renames one tag or merges several: renaming onto an existing tag is a merge anyway,
	 *  since a note cannot carry one twice.
	 */
	renameTags: (tags: string[], into: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_tags", { tags, into })),
	/**  A list rather than one tag at a time: one round trip per tag is one lock per tag. */
	deleteTags: (tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_tags", { tags })),
	/**
	 *  No note identifier: the palette fills an unsaved draft as readily as a saved note.
	 *  The database is read only for the global variables.
	 */
	fillPlaceholders: (content: string, values: { [key in string]: string }) => typedError<string, AppError>(__TAURI_INVOKE("fill_placeholders", { content, values })),
	/**
	 *  A command of its own rather than a `NotePatch` field, so `updated_at` stays put: filling a
	 *  field is not editing the note.
	 */
	setPlaceholderValues: (id: string, values: { [key in string]: string }) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("set_placeholder_values", { id, values })),
	listGlobalPlaceholders: () => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("list_global_placeholders")),
	/**  Stores the whole set: what is not sent is what the user removed. */
	setGlobalPlaceholders: (values: { [key in string]: string }) => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("set_global_placeholders", { values })),
	/**  `None` = every space, like [`crate::notes::view::NotesQuery::space_id`]. */
	listFolders: (spaceId: string | null) => typedError<Folder[], AppError>(__TAURI_INVOKE("list_folders", { spaceId })),
	/**
	 *  The second way to look at a space: folders as zones, their notes inside, the loose ones
	 *  beside them. It reads the whole space and marks what matches rather than narrowing, and
	 *  draws no folder chips — a chip naming the zone a card sits in is noise.
	 */
	boardView: (query: BoardQuery) => typedError<BoardView, AppError>(__TAURI_INVOKE("board_view", { query })),
	/**
	 *  Where the zones and the loose cards ended up, as one batch and one transaction: a gesture
	 *  cut short must not leave half a board. Filing is not here (see [`file_notes`]). This is
	 *  also the undo of [`arrange_board`], with the layout that one answered.
	 */
	saveBoardLayout: (zones: ZonePlacement[], cards: CardPlacement[]) => typedError<null, AppError>(__TAURI_INVOKE("save_board_layout", { zones, cards })),
	/**
	 *  Puts one space's board back in order, as far as `scope` allows, and answers the layout it
	 *  replaced: the only moment the old one still exists, for an undo.
	 */
	arrangeBoard: (spaceId: string, scope: BoardScope) => typedError<BoardArrangement, AppError>(__TAURI_INVOKE("arrange_board", { spaceId, scope })),
	createFolder: (draft: FolderDraft) => typedError<Folder, AppError>(__TAURI_INVOKE("create_folder", { draft })),
	renameFolder: (id: string, name: string) => typedError<Folder, AppError>(__TAURI_INVOKE("rename_folder", { id, name })),
	recolourFolder: (id: string, colour: FolderColour) => typedError<Folder, AppError>(__TAURI_INVOKE("recolour_folder", { id, colour })),
	/**
	 *  No refuge, unlike [`crate::spaces::delete_space`]: the notes come out loose, a legitimate
	 *  state.
	 */
	deleteFolder: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_folder", { id })),
	/**
	 *  A batch, like [`crate::notes::move_notes`]: the selection bar files a whole selection,
	 *  and a drop on the board is a batch of one. `folderId` absent unfiles.
	 */
	fileNotes: (ids: string[], folderId: string | null) => typedError<NoteFiling[], AppError>(__TAURI_INVOKE("file_notes", { ids, folderId })),
	/**  The undo of [`file_notes`]: each note goes back to the folder it left, or to loose. */
	fileNotesBack: (filings: NoteFiling[]) => typedError<number, AppError>(__TAURI_INVOKE("file_notes_back", { filings })),
	listSpaces: () => typedError<Space[], AppError>(__TAURI_INVOKE("list_spaces")),
	createSpace: (draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("create_space", { draft })),
	renameSpace: (id: string, draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("rename_space", { id, draft })),
	pinSpace: (id: string, pinned: boolean) => typedError<Space, AppError>(__TAURI_INVOKE("pin_space", { id, pinned })),
	deleteSpace: (id: string, targetSpaceId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_space", { id, targetSpaceId })),
	/**
	 *  ⚠️ `path` is not checked, and cannot be: it is the native picker's answer. With
	 *  `read_attachment` this reads any file the account can read into the `WebView`, and what keeps
	 *  that harmless is the CSP — `script-src 'self'`, nothing remote — not this function.
	 */
	attachFile: (noteId: string, path: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_file", { noteId, path })),
	/**  The bytes do not cross the bridge: the clipboard is read natively, as raw RGBA. */
	attachClipboardImage: (noteId: string, fileName: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_clipboard_image", { noteId, fileName })),
	listAttachments: (noteId: string) => typedError<Attachment[], AppError>(__TAURI_INVOKE("list_attachments", { noteId })),
	readAttachment: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("read_attachment", { id })),
	/**
	 *  The call starts from Rust: opening a path from the front end would mean allowing
	 *  `opener:allow-open-path` over a whole directory.
	 * 
	 *  ⚠️ The one place a decrypted copy reaches the disk: the program the desktop picks reads a
	 *  path. It goes under the profile's `open/` ([`sealed::plaintext_directory`]) and is swept
	 *  on exit and at the next launch, since that program may still hold it on close.
	 */
	openAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_attachment", { id })),
	/**  The path comes from a native picker; the write stays here. */
	saveAttachment: (id: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("save_attachment", { id, path })),
	deleteAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_attachment", { id })),
	/**
	 *  A `None` passphrase writes the file in the clear: the library's key protects what is
	 *  on this machine, never what leaves it.
	 */
	exportNotes: (path: string, scope: ExportScope, passphrase: string | null) => typedError<ExportReport, AppError>(__TAURI_INVOKE("export_notes", { path, scope, passphrase })),
	/**
	 *  The file is read before the lock is taken: parsing a large export while holding the
	 *  connection would block every other command for the length of it.
	 */
	importNotes: (path: string, passphrase: string | null) => typedError<ImportReport, AppError>(__TAURI_INVOKE("import_notes", { path, passphrase })),
	/**  Nothing is sent anywhere: "share" stops at the clipboard. */
	shareNotes: (ids: string[]) => typedError<string, AppError>(__TAURI_INVOKE("share_notes", { ids })),
	/**  Whether an import will want a phrase, so the interface can ask before it starts. */
	exportIsProtected: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("export_is_protected", { path })),
	vaultState: () => typedError<VaultState, AppError>(__TAURI_INVOKE("vault_state")),
	/**
	 *  The first launch. Refuses a library that already has a key file: that file is the only
	 *  way into the notes beside it.
	 */
	createVault: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("create_vault", { passphrase })),
	/**
	 *  Off the main thread: deriving the key is slow on purpose, and would freeze the window over
	 *  every attempt.
	 */
	unlockVault: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("unlock_vault", { passphrase })),
	/**
	 *  A new phrase over the same library, from the preferences panel.
	 * 
	 *  Not a re-encryption: the key the notes are sealed with is rewrapped, and the library stays
	 *  open on it.
	 */
	changePassphrase: (current: string, next: string) => typedError<PassphraseChange, AppError>(__TAURI_INVOKE("change_passphrase", { current, next })),
	/**
	 *  Sets the damaged library aside so the next unlock starts on a fresh one.
	 * 
	 *  Answers the folder it moved everything into, so the interface can say where.
	 */
	setAsideDamagedLibrary: () => typedError<string, AppError>(__TAURI_INVOKE("set_aside_damaged_library")),
	/**
	 *  Archives a library whose passphrase was forgotten, so a fresh one can be started.
	 * 
	 *  Nothing is recovered: the notes leave sealed, under the forgotten phrase, and `vault.json`
	 *  goes with them for the day the phrase comes back.
	 */
	archiveLockedLibrary: () => typedError<string, AppError>(__TAURI_INVOKE("archive_locked_library")),
	/**  The copies that exist, newest first, for the panel that lists them. */
	listBackups: () => typedError<Backup[], AppError>(__TAURI_INVOKE("list_backups")),
	/**
	 *  Puts a copy back, and answers where the library it replaced was moved to.
	 * 
	 *  ⚠️ Closes the library first, under the lock every command takes: renaming a database out
	 *  from under a live connection loses it. Every command then answers `Locked`, which sends
	 *  the interface back to the gate to ask for the restored copy's phrase.
	 */
	restoreBackup: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("restore_backup", { id })),
	/**  The libraries, and which one is open. */
	listLibraries: () => typedError<Registry, AppError>(__TAURI_INVOKE("list_libraries")),
	/**  Adds one, and leaves it closed: opening it is a second, deliberate gesture. */
	createLibrary: (name: string) => typedError<LibraryEntry, AppError>(__TAURI_INVOKE("create_library", { name })),
	/**
	 *  Closes whatever is open and points the registry at another one.
	 * 
	 *  ⚠️ The connection `Mutex` is emptied under the lock every command takes: they all answer
	 *  `Locked` afterwards, which sends the interface back to the gate for the other passphrase.
	 */
	openLibrary: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_library", { id })),
	renameLibrary: (id: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_library", { id, name })),
	/**
	 *  Erases a library and everything in it.
	 * 
	 *  Refused on the open one: deleting files under a live connection takes the process down.
	 */
	deleteLibrary: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_library", { id })),
	appChangelog: () => __TAURI_INVOKE<ChangelogRelease[]>("app_changelog"),
	/**  The notes the updater hands over, read with the same grammar as the file. */
	releaseNotes: (markdown: string) => __TAURI_INVOKE<ChangelogSection[]>("release_notes", { markdown }),
	/**
	 *  Replaces only the menu when the tray exists, so a language change does not flicker. No
	 *  `Result`: without a tray, `tray_exists` is what stops closing from hiding the window.
	 */
	syncTray: (labels: TrayLabels) => __TAURI_INVOKE<void>("sync_tray", { labels }),
	/**  The native side can only fail silently, and a log line is not an interface. */
	setGlobalShortcuts: (bindings: ShortcutBindings) => __TAURI_INVOKE<string[]>("set_global_shortcuts", { bindings }),
	setWindowBehavior: (behavior: WindowBehavior) => __TAURI_INVOKE<void>("set_window_behavior", { behavior }),
};

/* Constants */
export const APP_METADATA = {"name":"DevNotes","repository":"https://github.com/vmillet-dev/devnotes-rs","author":"Valentin MILLET","authorHandle":"@vmillet-dev","rustVersion":"1.97.1"} as const;

export const AUTOMATIC_BACKUPS_KEY = "devnotes.automaticBackups" as const;

export const DEFAULT_SHORTCUTS = {"capture":"Ctrl+Alt+V","newNote":"Ctrl+Alt+N","palette":"Ctrl+Alt+P"} as const;

export const FIELD_NAME_PATTERN = "^[A-Za-z0-9_-]+$" as const;

export const GLOBAL_ACTION_EVENT = "devnotes:action" as const;

export const MINIMUM_PASSPHRASE_LENGTH = 12 as const;

export const PREFERENCES_FILE = "preferences.json" as const;

/* Types */
export type AlgorithmFamily = "hmac" | "rsa" | "rsaPss" | "ecdsa" | "edDsa" | 
/**  `alg: none`: nothing signs it. */
"unsigned" | "unknown";

export type AppError = {
	code: ErrorCode,
	/**  Values to interpolate into the translated message, e.g. `{ "name": "Personal" }`. */
	params: { [key in string]: string },
	detail: string,
};

export type Attachment = {
	id: string,
	noteId: string,
	/**  The original name, the one displayed. Never used as a path. */
	fileName: string,
	mimeType: string,
	/**  `u32` and not `u64`: Specta refuses what JSON cannot carry without loss. */
	byteSize: number,
	createdAt: string,
};

/**
 *  One copy, as the interface lists it. `bytes` is `f64` because specta refuses the integer
 *  types JSON cannot carry exactly.
 */
export type Backup = {
	/**  The folder's name, which is its stamp, and what a restore asks for. */
	id: string,
	takenAt: string,
	/**  The database alone: the attachments are shared with the library and the other copies. */
	bytes: number | null,
	/**  Whether the key file travelled with it: without one, restoring loses the library. */
	openable: boolean,
};

export type Base64FileAnswer = 
/**  A file keeps the two Base64 alone: the other encodings of a megabyte are noise. */
{ kind: "encoded"; name: string; bytes: number; base64: string; base64Url: string } | { kind: "failed"; problem: FileProblem };

export type BlockKind = "thisNetwork" | "private" | "sharedAddressSpace" | "loopback" | "linkLocal" | "documentation" | "benchmarking" | "multicast" | "reserved" | "broadcast" | "public" | "unspecified" | "ipv4Mapped" | "nat64" | "uniqueLocal" | "global" | 
/**  Wider than a special range it holds: no one sentence describes it. */
"mixed";

/**  What a tidy-up did, and what it takes to walk it back. */
export type BoardArrangement = {
	/**  What actually moved: a board already in order moves nothing, and opens no undo. */
	moved: number,
	previous: BoardLayout,
};

export type BoardFrame = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**
 *  A whole board's geometry: every zone's frame and every loose card's place. What a tidy-up
 *  writes, and, read back first, what its undo puts back.
 */
export type BoardLayout = {
	zones: ZonePlacement[],
	cards: CardPlacement[],
};

/**  `flatten`: the front end draws this with the same card component the canvas uses. */
export type BoardNote = {
	/**
	 *  Dimmed in place rather than reflowed: spatial memory is what the board has that the
	 *  date view does not.
	 */
	matches: boolean,
	/**  `None` inside a zone, where a card flows; `Some` only on the free background. */
	position: BoardPoint | null,
} & DisplayNote;

export type BoardPoint = {
	x: number,
	y: number,
};

export type BoardQuery = {
	/**  Required, unlike `NotesQuery::space_id`: a board across every space has no zones. */
	spaceId: string,
	search: string,
	filter: NoteFilter,
	tags: string[],
	languages: Language[],
	kinds: NoteKind[],
	priorities: Priority[],
	now: string,
};

/**
 *  How much of a board a tidy-up is allowed to move.
 * 
 *  Two scopes rather than one with a warning: what goes to pieces is the loose cards, and a
 *  zone placed and sized by hand is the only manual work the board holds.
 */
export type BoardScope = 
/**  The loose cards alone, flowed under the zones as they stand. */
"looseCards" | 
/**
 *  The zones as well: reading order, sized to their contents. Overwrites every frame
 *  set by hand.
 */
"everything";

export type BoardView = {
	zones: BoardZone[],
	loose: BoardNote[],
	/**
	 *  The space's, like `NotesView`'s: facets drawn from filtered notes would empty the
	 *  rails on the first selection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	isFiltering: boolean,
	matched: number,
	/**  The surface to pan over, sized from what is on it. */
	width: number,
	height: number,
};

export type BoardZone = {
	folder: Folder,
	frame: BoardFrame,
	notes: BoardNote[],
};

export type ByteEncoding = "base64" | 
/**  `-` and `_` for `+` and `/`, without padding: what a URL or a JWT carries. */
"base64Url" | "base32" | "hex" | "binary" | "decimal";

/**  What a calendar counts: whole months first, each of its own length, then the wall clock. */
export type CalendarGap = {
	years: number,
	months: number,
	days: number,
	hours: number,
	minutes: number,
	seconds: number,
};

export type CardNetwork = "visa" | "mastercard" | "americanExpress" | "discover" | "dinersClub" | "jcb" | "unionPay" | "maestro";

/**
 *  One loose card that moved. Filing is not here: it goes through `file_notes`, whose answer
 *  the undo puts back. A position has no undo of its own.
 */
export type CardPlacement = {
	noteId: string,
	position: BoardPoint,
};

export type CaseAnswer = {
	/**  Empty for a text without a word. */
	conversions: CaseConversion[],
	/**  What the converters work from: the first line holding a word, or the whole phrase. */
	words: string[],
	/**  For a URL: transliterated, where the code cases only strip accents. Empty for no word. */
	slug: string,
};

export type CaseConversion = {
	case: TextCase,
	group: CaseGroup,
	value: string,
};

/**
 *  What a case is for. The code cases strip accents when asked; the text cases keep them, and
 *  keep the apostrophe that binds an elided word to the next (`l'été`).
 */
export type CaseGroup = "code" | "text";

export type CaseRequest = {
	text: string,
	/**  The code cases only: `été` is `ete` in `snake_case` and stays `été` in a title. */
	stripAccents: boolean,
	/**  Each line on its own; off, the whole text is one phrase. */
	perLine: boolean,
	titleCaseLanguage: TitleLanguage,
	slug: SlugOptions,
};

export type ChangelogRelease = {
	/**  `0.1.1`, or whatever the heading names. Square brackets are dropped. */
	version: string,
	/**  `None` when the heading carries no date; never invented. */
	date: string | null,
	sections: ChangelogSection[],
};

/**  One `### ` heading, or the anonymous one a release with no category gets.        */
export type ChangelogSection = {
	/**  Empty for that anonymous category: the front then renders no heading. */
	title: string,
	items: ChangelogSpan[][],
};

export type ChangelogSpan = {
	kind: SpanKind,
	text: string,
};

export type CharacterSet = "lowercase" | "uppercase" | "digits" | "symbols";

export type CheckAnswer = { kind: "luhn"; grouped: string; 
/**  Its digits, counted. */
length: number; valid: boolean; 
/**  The last digit the rest asks for. */
expectedLast: number; 
/**  The number with a check digit appended, as if it had none yet. */
completed: string; network: CardNetwork | null; guessed: boolean } | { kind: "iban"; country: string; printed: string; 
/**  The two digits after the country, as typed. */
checkDigits: string; 
/**  Its characters, spaces left out. */
length: number; verdict: IbanVerdict; guessed: boolean } | 
/**  One-based, in characters. */
{ kind: "unreadable"; at: number } | { kind: "tooShort" };

export type CheckKind = "luhn" | "iban";

export type CheckRequest = {
	text: string,
	/**  Read as this kind rather than by its shape. */
	kind: CheckKind | null,
};

/**
 *  No identifier: the position is the identity — `note_items` is keyed on
 *  `(note_id, position)`, and a write rewrites the whole list.
 */
export type ChecklistItem = {
	text: string,
	done: boolean,
};

export type CidrAnswer = {
	block: CidrBlock | null,
	problem: CidrProblem | null,
	membership: CidrMembership,
	/**  The prefixes offered as chips: the next three. */
	splitChoices: number[],
	split: CidrSplit | null,
	masks: MaskRow[],
	plan: CidrPlan | null,
	summary: CidrSummary | null,
};

export type CidrBlock = {
	family: IpFamily,
	cidr: string,
	/**  The address as typed, host bits and all: what a prefix chosen in the table applies to. */
	typed: string,
	prefix: number,
	hostBits: number,
	/**  The address had host bits set: `cidr` is its network. */
	normalised: boolean,
	/**  The network address in binary, cut where the host bits start. */
	binaryNetwork: string,
	binaryHost: string,
	kind: BlockKind,
	/**  The special range the block lies in, when it names one: `10.0.0.0/8`. */
	range: string | null,
	network: string,
	/**  IPv4 only. */
	mask: string | null,
	inverseMask: string | null,
	first: string,
	last: string,
	/**  IPv4 from `/30` up: `/31` and `/32` have none, nor IPv6. */
	broadcast: string | null,
	/**  Decimal digits: an IPv6 count passes what a JSON number holds. */
	addresses: string,
	usable: string,
	forms: CidrForms,
};

export type CidrForms = {
	integer: string,
	/**  IPv4 in hexadecimal, IPv6 with every zero written out. */
	expanded: string,
	reverse: ReverseDns,
};

export type CidrMembership = { kind: "empty" } | { kind: "unreadable" } | { kind: "outside" } | 
/**  Counted from the network address, which is host 0. */
{ kind: "inside"; host: string };

export type CidrPlan = {
	/**  In address order, which is the largest need first; the unreadable lines last. */
	lines: PlanLine[],
	/**  What is left of the block, as the fewest blocks. */
	free: string[],
};

export type CidrProblem = "unreadable" | "prefixTooLong" | "maskWithHoles" | "wrongFamily";

export type CidrRequest = {
	network: string,
	/**  `None` reads the family from the text. */
	family: IpFamily | null,
	member: string,
	split: number | null,
	/**  One need a line, a name and a host count, placed in the block. */
	plan: string,
	/**  Blocks, addresses and ranges, one a line, summarised whatever the block. */
	list: string,
};

export type CidrSplit = {
	prefix: number,
	subnets: Subnet[],
	/**  How many past `SUBNETS_SHOWN`, in decimal digits. */
	more: string,
};

export type CidrSummary = {
	/**  IPv4 first, then IPv6, each when the list holds some. */
	families: FamilySummary[],
	unreadable: string[],
};

export type Class = "owner" | "group" | "others";

/**  A row of the grid: its four boxes are four booleans, not a state machine. */
export type ClassRights = {
	class: Class,
	read: boolean,
	write: boolean,
	execute: boolean,
	/**  Setuid for the owner, setgid for the group, the sticky bit for the others. */
	special: boolean,
};

export type CodecDirection = "encode" | "decode";

export type ColourAnswer = {
	colour: ColourReading,
	against: ColourReading,
	contrast: Contrast | null,
};

export type ColourReading = { kind: "read"; given: Notation; notations: Notations; 
/**  What the window paints: in sRGB, always. */
swatch: string; 
/**  An OKLCH colour sRGB cannot show, brought inside at the same lightness and hue. */
outOfGamut: boolean } | { kind: "invalid" } | { kind: "empty" };

export type ColourRequest = {
	colour: string,
	/**  The background the contrast is measured on; empty for none. */
	against: string,
};

/**  The connections every estimate is also given for, by their rate in bits per second. */
export type Connection = "fibre" | "mobile4g" | "adsl";

export type ConnectionEstimate = {
	/**  `None` for the rate typed. */
	connection: Connection | null,
	/**  In bits per second, exact. */
	rate: string,
	span: TransferTime,
};

export type Contrast = {
	ratio: number | null,
	aa: TextSizes,
	aaa: TextSizes,
	/**  `None` once AAA holds for body text: nothing left to reach. */
	fix: ContrastFix | null,
};

/**  The nearest text colour that reaches the next level on this background, for body text. */
export type ContrastFix = { kind: "found"; level: WcagLevel; hex: string } | 
/**  Neither black nor white reaches it on this background. */
{ kind: "unreachable"; level: WcagLevel };

export type ConvertAnswer = { kind: "converted"; text: string; 
/**  The keys left out, as `JSONPath`s: a `null` TOML cannot write. */
dropped: string[] } | 
/**  The text given does not parse: one-based line and column, in characters. */
{ kind: "unreadable"; line: number; column: number } | 
/**  It parses, but the other format cannot hold it: `path` is a `JSONPath`. */
{ kind: "impossible"; crossing: Crossing; path: string };

export type ConvertRequest = {
	text: string,
	from: DataFormat,
	to: DataFormat,
};

export type CronAnswer = { kind: "read"; 
/**  What a macro stands for: `@daily` is `0 0 * * *`. */
expanded: string | null; fields: FieldReading[]; 
/**  Both day fields restricted: either one matching is enough, as in cron. */
bothDays: boolean; zone: string; runs: Run[]; check: CronCheck | null } | 
/**  `@reboot` runs when the machine starts: no time to give. */
{ kind: "reboot" } | { kind: "refused"; field: CronField | null; token: string; 
/**  One-based, in characters of the expression as typed. */
at: number; problem: CronProblem } | { kind: "unknownZone"; zone: string };

export type CronCheck = { kind: "checked"; matches: boolean; at: string } | { kind: "unreadable"; at: number } | { kind: "skipped" };

export type CronField = "second" | "minute" | "hour" | "dayOfMonth" | "month" | "dayOfWeek";

export type CronProblem = "empty" | "fieldCount" | "unknownMacro" | "unknownName" | "notANumber" | "outOfRange" | "reversedRange" | "zeroStep" | 
/**  A special character this field does not take: `L` in the minutes. */
"notHere" | 
/**  Read here, refused by the scheduler: nothing more precise to say. */
"refused";

export type CronRequest = {
	expression: string,
	/**  `None` is the machine's zone. */
	zone: string | null,
	/**  A date to test against the expression, read in `zone`; empty asks nothing. */
	check: string,
};

export type Crossing = 
/**  TOML has no `null`, and one in a list cannot be left out without moving the others. */
"tomlNull" | 
/**  A TOML document is a table: its root cannot be a list or a value. */
"tomlRoot" | 
/**  An XML document has one root element: an object of one key. */
"xmlRoot" | 
/**  A key XML cannot take as an element or an attribute name. */
"xmlName" | 
/**  An `@attribute` holds a value, not an object or a list. */
"xmlAttribute";

export type DataFormat = "json" | "toml" | "xml" | "yaml";

export type DatedClaim = {
	name: string,
	iso: string,
	/**  For how long ago or how far off, which the page writes and ages. */
	epochMilliseconds: number | null,
};

export type DecodeAnswer = {
	readAs: ByteEncoding,
	/**  Read by its shape rather than as asked. */
	guessed: boolean,
	/**  The other readings its shape allows: `deadbeef` is hexadecimal and Base64 alike. */
	also: ByteEncoding[],
	decoded: DecodedBytes,
};

export type DecodeProblem = 
/**  A character outside the alphabet, or padding in the middle. */
"character" | 
/**
 *  A length nothing of this encoding ends on: one Base64 character past a group, an odd
 *  number of hex digits, bits that are no whole byte.
 */
"length" | 
/**  A last character whose bits say the text was cut. */
"truncated" | 
/**  A decimal byte past 255. */
"tooLarge";

export type DecodeRequest = {
	text: string,
	/**  `None` reads it by its shape. */
	reading: ByteEncoding | null,
};

export type DecodedBytes = { kind: "text"; text: string; bytes: number } | 
/**  Not UTF-8: what it starts with, in hexadecimal, and an offer to save it. */
{ kind: "binary"; bytes: number; preview: string } | 
/**  `at` counts characters of the text as given, spaces and line breaks included. */
{ kind: "invalid"; problem: DecodeProblem; at: number | null; character: string | null };

/**  One line of a kept body, compared with the text restoring it would replace. */
export type DiffLine = 
/**  In both: restoring leaves it where it is. */
{ kind: "kept"; text: string } | 
/**  Only in the kept body: restoring brings it back. */
{ kind: "restored"; text: string } | 
/**  Only in the current text: restoring takes it away. */
{ kind: "dropped"; text: string } | 
/**  Unchanged lines too far from any change to be worth reading. */
{ kind: "skipped"; count: number };

export type DigestEncoding = "hex" | "base64";

/**  What a digest is from its length alone: an HMAC has the shape of the hash it uses. */
export type DigestShape = { kind: "hex"; characters: number; 
/**  Empty when no digest has this length. */
algorithms: HashAlgorithm[] } | { kind: "base64"; bytes: number; algorithms: HashAlgorithm[] } | 
/**  Neither alphabet. */
{ kind: "unknown" };

export type DigestValue = {
	algorithm: HashAlgorithm,
	bits: number,
	value: string,
};

export type DigestVerdict = { kind: "matches"; algorithm: HashAlgorithm; encoding: DigestEncoding } | { kind: "noMatch"; shape: DigestShape };

/**  `flatten`: the front end has a single note type. */
export type DisplayNote = {
	footer: NoteFooter,
	expiringSoon: boolean,
	/**  The list is derived from the text; the values are persisted. */
	placeholders: Placeholder[],
	/**  Filled in afterwards by whoever holds a connection: `decorate` reads no database. */
	attachmentCount: number,
	/**
	 *  Resolved in a pass of its own, like [`Self::attachment_count`]: the front end
	 *  never joins a `folder_id` against a list it happens to hold.
	 */
	folder: NoteFolder | null,
	/**
	 *  What copying yields when that is not the content, so `checklist::to_markdown` stays
	 *  the only place the `- [x] ` syntax exists.
	 */
	copyText: string | null,
	/**
	 *  Filled in afterwards by `view::build`; `None` outside a search, and for a note
	 *  found by its own title.
	 */
	searchHit: SearchHit | null,
	/**  `content` holds only its first lines: a list sends previews, `get_note` the body. */
	truncated: boolean,
	/**
	 *  A Note's lines as its card draws them, cut like `content`; empty for the other kinds
	 *  and outside a list.
	 */
	outline: OutlineLine[],
} & Note;

export type DurationAnswer = { kind: "read"; negative: boolean; parts: DurationParts; iso: string; 
/**  Typed as words, « 1h30 », rather than in ISO 8601. */
fromWords: boolean; 
/**  `None` with years or months: neither has a fixed length in seconds. */
totals: DurationTotals | null } | 
/**  One-based, in characters. */
{ kind: "unreadable"; at: number; problem: DurationProblem };

/**  Each part as typed: a fraction is allowed on the last one only, so they are `f64`. */
export type DurationParts = {
	years: number | null,
	months: number | null,
	weeks: number | null,
	days: number | null,
	hours: number | null,
	minutes: number | null,
	seconds: number | null,
};

export type DurationProblem = 
/**  Not what an ISO duration or a unit of words may hold here. */
"unexpected" | 
/**  `P` or `PT` with nothing after it. */
"empty" | 
/**  A unit after a smaller one: `PT30M1H`. */
"outOfOrder" | "repeated" | 
/**  A fraction on a part that is not the last. */
"fractionNotLast";

/**  A day is counted as 24 hours, and a week as 7 of them. */
export type DurationTotals = {
	seconds: number | null,
	minutes: number | null,
	hours: number | null,
};

export type DurationsAnswer = {
	/**  Where a date written without an offset is read: the machine's zone, UTC without one. */
	zone: string,
	/**  `None` until both dates are typed. */
	gap: GapAnswer | null,
	duration: DurationAnswer | null,
};

export type DurationsRequest = {
	from: string,
	to: string,
	duration: string,
};

/**  What a clock counts between the two instants, cut several ways. */
export type Elapsed = {
	days: number,
	hours: number,
	minutes: number,
	seconds: number,
	weeks: number,
	weekDays: number,
	totalHours: number,
	totalMinutes: number,
};

export type EncodeRequest = {
	text: string,
	/**  Hexadecimal and binary, a space between bytes. Decimal always has one. */
	spaced: boolean,
	uppercase: boolean,
};

export type Encodings = {
	characters: number,
	bytes: number,
	wide: WideCharacter | null,
	base64: string,
	base64Url: string,
	base32: string,
	hex: string,
	binary: string,
	decimal: string,
};

export type EndingCounts = {
	lf: number,
	crlf: number,
	cr: number,
};

/**
 *  ⚠️ A new variant breaks the front-end build until `CODE_KEYS`
 *  (`core/services/errors/error-notifier.service.ts`) and both locales have its key.
 */
export type ErrorCode = "noteNotFound" | "spaceNotFound" | "duplicateSpaceName" | "folderNotFound" | "duplicateFolderName" | "attachmentNotFound" | "revisionNotFound" | "libraryNotFound" | "libraryOpen" | "lastLibrary" | "nothingToSetAside" | "backupNotFound" | "backupUnopenable" | "fileAccess" | "importFormat" | 
/**  The `field` parameter names the offending field. */
"invalidInput" | 
/**  Poisoned mutex: a command panicked while holding the connection. */
"storageUnavailable" | 
/**  The unlock screen clears the field on this one rather than showing a banner. */
"wrongPassphrase" | 
/**  A command ran before the library was unlocked. */
"locked" | 
/**  The import needs the phrase the export was protected with. */
"passphraseRequired" | 
/**  SQLite says the file is corrupt: the one code the interface answers with an action. */
"libraryDamaged" | "storage";

export type ExportReport = {
	notes: number,
	spaces: number,
	folders: number,
	/**  What went into the archive; a record whose file is missing is left out. */
	attachments: number,
	/**  `false` means readable by anyone who has the file: the interface says which it wrote. */
	protected: boolean,
};

/**  What an export takes. */
export type ExportScope = { kind: "library" } | { kind: "space"; spaceId: string } | 
/**  A selection: the ids the canvas had ticked. */
{ kind: "notes"; ids: string[] };

/**  How many of the space's notes carry a value. */
export type FacetCount<T> = {
	value: T,
	count: number,
};

export type FamilySummary = {
	family: IpFamily,
	blocks: string[],
	/**  The smallest single block holding every address listed. */
	supernet: string,
	/**  What the supernet holds beyond the list, in digits. */
	extra: string,
};

export type FieldReading = {
	field: CronField,
	text: string,
	/**  Zero-based character offsets in the expression read (the expansion of a macro). */
	start: number,
	end: number,
	pieces: Piece[],
};

export type FileProblem = "notFound" | "tooLarge" | "unreadable" | "unwritable";

export type FileType = "regular" | "directory" | "symbolicLink" | "characterDevice" | "blockDevice" | "namedPipe" | "socket";

export type FinalNewline = "keep" | "add" | "remove";

export type FinalNewlineChange = "unchanged" | "added" | "removed";

export type Folder = {
	id: string,
	spaceId: string,
	/**  Uniqueness is case-insensitive inside its space, decided by persistence. */
	name: string,
	colour?: FolderColour,
	createdAt: string,
};

/**
 *  Assigned on creation, changed from the zone menu after: drawing a folder stays one
 *  gesture. The five are the theme's accents, each with a light-theme twin.
 */
export type FolderColour = "blue" | "amber" | "purple" | "green" | "red";

export type FolderDraft = {
	spaceId: string,
	name: string,
};

export type Frequency = {
	character: string,
	/**  `U+0065 U+0301`: every code point of a character written with several. */
	codePoints: string,
	invisible: Invisible | null,
	count: number,
	/**  Of the characters counted, in percent. */
	share: number | null,
};

export type GapAnswer = { kind: "measured"; 
/**  `to` before `from`: the parts are the gap's size, the ISO form carries the sign. */
negative: boolean; calendar: CalendarGap; elapsed: Elapsed; 
/**  The calendar gap, `P6M22DT7H41M`. */
iso: string; transition: Transition | null; 
/**  The fields whose local time came twice: the earlier reading is taken. */
ambiguous: GapField[] } | 
/**  One-based, in characters. */
{ kind: "unreadable"; field: GapField; at: number } | 
/**  A local time the clocks skipped when they went forward. */
{ kind: "skipped"; field: GapField } | 
/**  Past the year 9999 either way. */
{ kind: "outOfRange"; field: GapField };

export type GapField = "from" | "to";

export type GenerateAnswer = { kind: "generated"; text: string; seed: number; unsupported: Unsupported[] } | { kind: "unreadable"; line: number; column: number } | 
/**  A schema is an object, or `true`. */
{ kind: "notASchema" };

export type GenerateRequest = {
	source: JsonSource,
	text: string,
	count: number,
	/**  The same seed and the same source draw the same documents; none draws one, and says which. */
	seed: number | null,
};

/**
 *  One event carrying a closed value rather than a topic per action: a mistyped topic is
 *  a silently inert subscription, and a new variant here stops the front compiling.
 */
export type GlobalAction = "capture" | "new-note" | "palette";

export type Granularity = "lines" | "words" | "characters";

/**  How the date view gathers its cards. A search or a facet still makes one flat list. */
export type Grouping = "date" | "priority" | "format" | "none";

/**  In the order the tool lists them. */
export type HashAlgorithm = "md5" | "sha1" | "sha256" | "sha384" | "sha512" | "sha3-256";

export type HashAnswer = { kind: "hashed"; bytes: number; endsWithNewline: boolean; digests: DigestValue[]; 
/**  `None` when no digest was pasted. */
verdict: DigestVerdict | null } | 
/**  No input: what the pasted digest is, by its shape. */
{ kind: "shaped"; shape: DigestShape } | { kind: "failed"; problem: FileProblem };

export type HashInput = { kind: "text"; text: string } | 
/**  Read here, a block at a time: its bytes never cross the bridge, whatever its size. */
{ kind: "file"; path: string };

export type HashRequest = {
	/**  `None` to read a pasted digest's shape alone. */
	input: HashInput | null,
	algorithms: HashAlgorithm[],
	encoding: DigestEncoding,
	/**  An HMAC when present. ⚠️ Zeroed once the digests are computed, and never stored. */
	key: string | null,
	/**  A digest to recognise, in any of the algorithms and either encoding. */
	expected: string | null,
};

export type IbanVerdict = { kind: "valid"; bban: string; bank: string | null; branch: string | null; 
/**  Where the country's format names one: France and Monaco. */
account: string | null; ribKey: RibKey | null } | 
/**  The check digits the rest asks for, and the IBAN written with them. */
{ kind: "wrongChecksum"; expected: string; corrected: string } | { kind: "wrongLength"; expected: number; found: number } | 
/**  The length is right, the characters are not the country's: letters where digits go. */
{ kind: "wrongFormat" } | { kind: "unknownCountry" };

export type IdInspection = { kind: "uuid"; version: number; variant: UuidVariant; 
/**  v1, v6 and v7 carry the time they were made, in UTC. */
created: string | null; nil: boolean; 
/**  v4 and v7 alone: the other versions draw nothing, or not where it can be told. */
random: RandomPart | null } | { kind: "ulid"; created: string; random: RandomPart } | { kind: "objectId"; created: string; counter: number; 
/**  Drawn once per process, not per identifier. */
random: RandomPart } | { kind: "ksuid"; created: string; random: RandomPart } | 
/**  The first CUID, deprecated by its author: its time is in plain sight. */
{ kind: "cuidV1"; created: string } | 
/**  The shape of an identifier that carries nothing to read. */
{ kind: "possible"; kinds: IdKind[] } | 
/**  The shape fits, the value does not: a ULID past `7ZZZZZZZZZ…`. */
{ kind: "outOfRange"; id: IdKind } | { kind: "unrecognised" };

export type IdKind = "uuidV4" | "uuidV7" | "ulid" | "nanoId" | "cuid2" | "objectId" | "ksuid";

export type IdentifiersRequest = {
	kind: IdKind,
	count: number,
	/**  For the kinds whose case carries nothing: UUID, ULID, `ObjectId`. */
	uppercase: boolean,
	/**  UUID only: `false` writes the 32 digits without their four hyphens. */
	hyphens: boolean,
	nanoLength: number,
	nanoAlphabet: NanoAlphabet,
};

/**  `skipped`: notes already present or whose space is missing, so an import can be replayed. */
export type ImportReport = {
	spacesCreated: number,
	/**  Matched by name inside the destination space, created when absent. */
	foldersCreated: number,
	notesImported: number,
	notesSkipped: number,
	/**
	 *  Brought down to the default for a `language` or `kind` this build does not know, and
	 *  counted so the loss is said.
	 */
	notesDegraded: number,
	attachmentsImported: number,
	/**
	 *  Records the archive named but did not carry: the only thing that says why a thumbnail
	 *  will never load.
	 */
	attachmentsMissing: number,
};

export type InstantAnswer = { kind: "read"; readAs: ReadAs; 
/**  The unit a number was read in, guessed from its magnitude or forced. */
magnitude: Magnitude | null; guessed: boolean; 
/**  Written without an offset, it was taken in the local zone. */
localAssumed: boolean; 
/**  A local time the clocks went through twice: the earlier reading is kept. */
ambiguous: boolean; forms: InstantForms } | 
/**  One-based, in characters: where the text stops making sense. */
{ kind: "unreadable"; at: number } | 
/**  A local time the clocks skipped when they went forward. */
{ kind: "skipped" } | 
/**  Beyond chrono's range, some 262 000 years either side of year 0. */
{ kind: "outOfRange" };

export type InstantForms = {
	unixSeconds: string,
	unixMilliseconds: string,
	unixMicroseconds: string,
	/**  An `i64` of nanoseconds reaches from 1677 to 2262 only. */
	unixNanoseconds: string | null,
	isoUtc: string,
	isoLocal: string,
	localOffset: string,
	/**  RFC 2822 writes a year of four digits, and none before year 0. */
	rfc2822: string | null,
	/**  The calendar facts are the local date's. 1 is Monday. */
	weekday: number,
	weekDate: string,
	week: number,
	ordinalDate: string,
	dayOfYear: number,
	/**  For the relative time the front formats: exact, since chrono's range stays under 2⁵³ ms. */
	epochMilliseconds: number | null,
};

export type InstantRequest = {
	text: string,
	/**  A number read in this unit rather than by its magnitude. */
	magnitude: Magnitude | null,
};

/**  What a reader cannot see, or would take for something else. */
export type Invisible = "space" | "tab" | "lineBreak" | "noBreakSpace" | "narrowNoBreakSpace" | "otherSpace" | "zeroWidthSpace" | "zeroWidthJoiner" | "zeroWidthNonJoiner" | "byteOrderMark" | "softHyphen" | "control";

export type IpFamily = "v4" | "v6";

export type JsonChange = {
	kind: JsonChangeKind,
	path: string,
	before: ValueSummary | null,
	after: ValueSummary | null,
};

export type JsonChangeKind = "added" | "removed" | "modified" | 
/**  The same keys, in another order: counted with the modifications. */
"reordered";

export type JsonDiffAnswer = { kind: "compared"; changes: JsonChange[]; counts: JsonDiffCounts; rows: JsonDiffRow[]; rowsTruncated: boolean; 
/**  RFC 6902, from A to B, as JSON. */
patch: string; 
/**  What each side was read as. */
formatA: DataFormat; formatB: DataFormat } | { kind: "unreadable"; side: JsonDiffSide; format: DataFormat; line: number; column: number };

export type JsonDiffCounts = {
	added: number,
	removed: number,
	modified: number,
};

export type JsonDiffLine = {
	/**  One-based, in that side's own text. */
	number: number,
	text: string,
};

export type JsonDiffRequest = {
	a: string,
	b: string,
	/**  `None` reads the side by its shape. */
	formatA: DataFormat | null,
	formatB: DataFormat | null,
	/**  On, `{"a":1,"b":2}` and `{"b":2,"a":1}` are the same document. */
	ignoreKeyOrder: boolean,
	/**  On, two strings that differ only by their spaces are the same. */
	ignoreWhitespace: boolean,
};

/**  One row of the side-by-side view: a side without a line is a gap. */
export type JsonDiffRow = {
	kind: JsonDiffRowKind,
	left: JsonDiffLine | null,
	right: JsonDiffLine | null,
	/**  The `JSONPath` of the value the row writes, for a change to scroll to. */
	path: string,
};

export type JsonDiffRowKind = "same" | "added" | "removed" | "modified";

export type JsonDiffSide = "a" | "b";

/**  One-based line and column, the column in UTF-16 units like the offset. */
export type JsonError = {
	reason: JsonErrorReason,
	line: number,
	column: number,
	offset: number,
};

export type JsonErrorReason = "unexpectedEnd" | "unexpectedCharacter" | "invalidNumber" | "invalidEscape" | "controlCharacter" | "trailingCharacters" | "tooDeep";

export type JsonGraph = {
	nodes: JsonNode[],
	width: number,
	height: number,
	/**  Opening everything asked was more than the front can draw: arrays stayed folded. */
	folded: boolean,
};

export type JsonKind = "object" | "array" | "string" | "number" | "boolean" | "null";

export type JsonLine = {
	depth: number,
	key: string,
	path: string,
	kind: JsonKind,
	value: string,
	size: number,
	span: Span,
	opens: boolean,
	open: boolean,
	hit: boolean,
};

export type JsonNode = {
	id: number,
	parent: number | null,
	path: string,
	/**  `$`, the key it is under, or `[0]`. */
	label: string,
	kind: JsonKind,
	/**  Keys or items, all of them: `rows` may hold fewer. */
	size: number,
	rows: JsonRow[],
	/**  Past `ROWS_PER_NODE`. */
	hiddenRows: number,
	span: Span,
	x: number,
	y: number,
	width: number,
	/**  The header line, one per row, one more for the rows left out. */
	height: number,
	hit: boolean,
};

export type JsonOpening = 
/**  Whole when small, its first level otherwise. */
{ kind: "initial" } | { kind: "all" } | 
/**
 *  `JSONPath`s, the root being always open: a path whose parent is closed stays closed.
 *  `reveal` opens every container above one more path — a match stepped to — so the front
 *  never has to take a path apart.
 */
{ kind: "paths"; paths: string[]; reveal?: string | null };

export type JsonQuery = {
	text: string,
	search: string,
	opening: JsonOpening,
};

export type JsonRow = {
	/**  `id`, or `[0]` in an array. */
	key: string,
	path: string,
	kind: JsonKind,
	/**  `"paid"`, `4900`, `{ … }`, `[ 3 ]`: cut to one line. */
	value: string,
	span: Span,
	/**  The node drawn for this value, when it is a container and open. */
	child: number | null,
	/**  Whether the value is a container, open or not. */
	opens: boolean,
	hit: boolean,
};

export type JsonSource = "schema" | "example";

export type JsonStats = {
	keys: number,
	/**  Container levels below the root: `{"a": {"b": 1}}` is 1. */
	depth: number,
	bytes: number,
};

export type JsonView = {
	/**  `None` is "JSON valide"; the rest is then empty. */
	error: JsonError | null,
	stats: JsonStats,
	graph: JsonGraph,
	tree: JsonLine[],
	treeTruncated: boolean,
	/**  Every entry the search found, in the document's order, open or not. */
	matches: string[],
	matchCount: number,
};

export type JwtAnswer = { kind: "decoded"; header: string; payload: string; 
/**  Both as one JSON document, which is what a note keeps: never the token. */
document: string; algorithm: string | null; family: AlgorithmFamily; signature: string; dates: DatedClaim[]; state: TokenState; verification: Verification } | { kind: "malformed"; problem: JwtProblem; segment: Segment | null; segments: number; 
/**  One-based, in characters of the token, where it could be said. */
at: number | null };

export type JwtProblem = 
/**  Not three segments; five is an encrypted token (JWE), not decoded here. */
"segmentCount" | "notBase64" | "notJson" | 
/**  JSON, but not an object. */
"notObject";

export type JwtRequest = {
	token: string,
	/**  Empty asks for no verification. Zeroed once used. */
	secret: string,
	secretIsBase64: boolean,
};

/**
 *  Closed: the front receives a generated union, so an unknown value stops compiling
 *  there instead of being refused at runtime.
 */
export type Language = "json" | "js" | "ts" | "py" | "rs" | "go" | "java" | "cs" | "php" | "c" | "sql" | "graphql" | "yml" | "toml" | "xml" | "html" | "css" | "scss" | "sh" | "md" | 
/**  Default, and the signal that the front end chose nothing. */
"txt";

/**  One library, as the interface lists it. */
export type LibraryEntry = {
	id: string,
	name: string,
	/**  Relative to the profile, so a profile copied to another machine still resolves. */
	directory: string,
	createdAt: string,
};

export type LineBreaksAnswer = {
	/**  In the text as it was given. */
	found: EndingCounts,
	text: string,
	/**  Endings rewritten to another kind. */
	converted: number,
	/**  Lines that lost spaces or tabs at their end. */
	trimmed: number,
	finalNewline: FinalNewlineChange,
};

export type LineBreaksRequest = {
	text: string,
	/**  `None` keeps each line's own ending. */
	ending: LineEnding | null,
	trimTrailing: boolean,
	finalNewline: FinalNewline,
};

export type LineEnding = "lf" | "crlf" | "cr";

export type LoremAnswer = {
	text: string,
	seed: number,
	/**  How many were made: the count asked, held within `at_most`, which the page says. */
	count: number,
	atMost: number,
};

export type LoremRequest = {
	unit: LoremUnit,
	count: number,
	/**  Opens on "Lorem ipsum dolor sit amet…", as the reader expects to recognise it. */
	opening: boolean,
	seed: number | null,
};

export type LoremUnit = "words" | "sentences" | "paragraphs";

export type Magnitude = "seconds" | "milliseconds" | "microseconds" | "nanoseconds";

export type MaskRow = {
	prefix: number,
	hostBits: number,
	/**  IPv4 only. */
	mask: string | null,
	wildcard: string | null,
	addresses: string,
	usable: string,
	/**  IPv6 only, up to `/64`: the `/64` networks, a LAN each, it holds. */
	networks64: string | null,
};

export type Mode = {
	/**  The twelve bits, `0o7777` at most. */
	bits: number,
	/**  Three digits, or four when a special bit is set: `755`, `4755`. */
	octal: string,
	symbolic: string,
	/**  `u=rwx,g=rx,o=rx`, what `chmod` takes to set exactly this mode. */
	chmodSymbolic: string,
	classes: ClassRights[],
};

export type ModeProblem = 
/**  Neither octal digits nor a mode string. */
"unreadable" | 
/**  A digit past 7. */
"notOctal" | 
/**  More than 0o7777. */
"tooLarge" | 
/**  A letter where this position of a mode string takes another. */
"unexpected" | 
/**  A mode string is nine letters, ten with the file type in front. */
"length";

export type ModeReading = { kind: "empty" } | { kind: "read"; mode: Mode; 
/**  Named by the letter a mode string of `ls -l` starts with. */
fileType: FileType | null; warnings: ModeWarning[] } | { kind: "refused"; problem: ModeProblem; 
/**  One-based, in characters. */
at: number };

/**  A mode that is probably a mistake: legal, but rarely what was meant. */
export type ModeWarning = 
/**  The group holds less than everybody: the others have a right it lacks. */
"othersOverGroup" | 
/**  The owner holds less than its group. */
"groupOverOwner" | 
/**  Anyone may write, and no sticky bit keeps each to their own files. */
"worldWritable" | 
/**  Setuid or setgid without the execute right it acts on: `S` in `ls -l`. */
"specialWithoutExecute";

export type NanoAlphabet = 
/**  `A-Za-z0-9_-`, `NanoID`'s own. */
"urlSafe" | "alphanumeric" | "hexLower" | "digits";

export type Notation = "hex" | "rgb" | "hsl" | "oklch";

export type Notations = {
	hex: string,
	rgb: string,
	hsl: string,
	oklch: string,
};

export type Note = {
	id: string,
	spaceId: string,
	/**
	 *  The folder travels with an export; where its zone sits must never join this model,
	 *  which `transfer::Bundle` deserialises.
	 */
	folderId?: string | null,
	title: string,
	language: Language,
	content: string,
	/**  Breadcrumb, e.g. "API Gateway / Auth". Can be empty. */
	source: string,
	tags: string[],
	pinned: boolean,
	createdAt: string,
	updatedAt: string,
	lifecycle: NoteLifecycle,
	/**
	 *  `default`: `transfer::Bundle` deserialises `Note`, and export files from before todo
	 *  lists carry no such key.
	 */
	kind?: NoteKind,
	/**  Set by `set_priority` alone, which leaves `updated_at` alone: triaging is not editing. */
	priority?: Priority,
	/**  A checklist has these instead of `content`. */
	items?: ChecklistItem[],
	/**  Written by `set_placeholder_values` alone, which leaves `updated_at` alone. */
	placeholderValues?: { [key in string]: string },
};

export type NoteDraft = {
	spaceId: string,
	/**  Set by the two places that file a new note: the board and the inside of a folder. */
	folderId?: string | null,
	title: string,
	language: Language,
	content: string,
	source: string,
	tags: string[],
	pinned: boolean,
	lifecycle: NoteLifecycle,
	kind?: NoteKind,
	priority?: Priority,
	items?: ChecklistItem[],
};

/**  Which folder each note left, the only thing that can put a filing back; `None` was loose. */
export type NoteFiling = {
	noteId: string,
	folderId?: string | null,
};

/**  `Untriaged` = notes with a deadline, those whose fate is not decided. */
export type NoteFilter = "all" | "pinned" | "untriaged";

/**
 *  What a card shows, resolved by the back end: the front end never joins an id against
 *  a list it happens to hold.
 */
export type NoteFolder = {
	id: string,
	name: string,
	colour: FolderColour,
};

/**
 *  The decision, not the rendering: the dated variants carry a date and not a label,
 *  so "4 min ago" ages on screen without a round trip.
 */
export type NoteFooter = { kind: "source"; value: string } | { kind: "expiry"; at: string } | 
/**  Since the last edit. */
{ kind: "age"; at: string } | 
/**  Since the note was made: the age, when the list is sorted by creation. */
{ kind: "created"; at: string };

/**
 *  Closed, like `Language`: the front receives a generated union, so an unknown
 *  value stops compiling there. Declared in the order the kind rail counts them.
 */
export type NoteKind = 
/**  Default, and what every note written before todo lists reads back as. */
"snippet" | 
/**  Prose, written in the rich editor and stored as Markdown. */
"note" | "checklist";

export type NoteLifecycle = { kind: "permanent" } | { kind: "expires"; at: string };

/**  What the date view is ordered by. The board keeps the places its cards were given. */
export type NoteOrder = {
	key: SortKey,
	direction: SortDirection,
};

/**
 *  ⚠️ A field set to `None` stays unchanged, and `#[specta(optional)]` makes the key omissible
 *  in TypeScript: without it the front sends `null` for what it does not touch, overwriting it.
 */
export type NotePatch = {
	spaceId?: string | null,
	title?: string | null,
	language?: Language | null,
	content?: string | null,
	source?: string | null,
	tags?: string[] | null,
	pinned?: boolean | null,
	lifecycle?: NoteLifecycle | null,
	kind?: NoteKind | null,
	/**  Replaces the whole list, like `tags`: a position is all the identity an item has. */
	items?: ChecklistItem[] | null,
};

/**  Where a note sat before a batch moved it — the only thing that can put it back. */
export type NotePlacement = {
	noteId: string,
	spaceId: string,
};

/**  A note's priority before a batch moved it: its undo puts back each note's own. */
export type NotePriority = {
	noteId: string,
	priority: Priority,
};

export type NoteSection = {
	key: NoteSectionKey,
	/**  Unique among the sections, where the key is not: every format section is `format`. */
	id: string,
	/**  What a priority or a format section gathers, which the front names. */
	group: SectionGroup | null,
	hasExpiringNotes: boolean,
	notes: DisplayNote[],
	showCreateGhost: boolean,
};

/**  A translation key on the front-end side: no readable label crosses the bridge. */
export type NoteSectionKey = "pinned" | "today" | "week" | "older" | "results" | "priority" | "format" | "all";

/**
 *  One tag on one note: a batch answers pair by pair, so its undo cannot strip a tag the note
 *  already carried.
 */
export type NoteTag = {
	noteId: string,
	tag: string,
};

export type NotesQuery = {
	/**  `None` = every space: a choice, not an absence of one. */
	spaceId: string | null,
	/**
	 *  `None` = every folder, filed or not. No "unfiled" filter: the absence of a chip already
	 *  says it.
	 */
	folderId?: string | null,
	search: string,
	filter: NoteFilter,
	/**  A note passes if it carries at least one of these tags. */
	tags: string[],
	languages: Language[],
	kinds: NoteKind[],
	priorities: Priority[],
	/**  Left out by the palette: the modification date, newest first. */
	order?: NoteOrder,
	grouping?: Grouping,
	now: string,
	/**
	 *  `Date#getTimezoneOffset()`, whose sign is the opposite of the offset (−120 for
	 *  UTC+2). Sections reason in local days.
	 */
	tzOffsetMinutes: number,
	/**  Their own section when the view is chronological, the head of the list when flat. */
	pinnedFirst: boolean,
};

export type NotesView = {
	sections: NoteSection[],
	/**
	 *  The space's, not the current filter's: facets drawn from filtered notes would empty
	 *  the rail on the first selection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	kindCounts: FacetCount<NoteKind>[],
	priorityCounts: FacetCount<Priority>[],
	isFiltering: boolean,
	/**  `u32` and not `usize`: Specta refuses what JSON cannot carry exactly. */
	matched: number,
};

export type Operand = "x" | "y";

/**  One line of a Note as a card draws it, read from its Markdown by `notes::markdown`. */
export type OutlineLine = { kind: "heading"; text: string } | { kind: "text"; text: string } | 
/**  `marker` is `•` or the item's number. */
{ kind: "item"; text: string; depth: number; marker: string } | { kind: "task"; text: string; depth: number; done: boolean } | 
/**  A code block, its lines as written. */
{ kind: "code"; text: string };

/**
 *  What a change reached. `backupsLeft` is the honest half: a key file copied somewhere else
 *  still opens with the retired phrase.
 */
export type PassphraseChange = {
	backupsRewrapped: number,
	backupsLeft: number,
};

export type PasswordAnswer = { kind: "generated"; passwords: string[]; entropyBits: number | null; strength: Strength } | 
/**  Every character set was left out. */
{ kind: "noCharacters" };

export type PasswordRequest = {
	length: number,
	/**  Each chosen set is in every password drawn. */
	sets: CharacterSet[],
	avoidLookAlikes: boolean,
	count: number,
};

/**  The two numbers of one question, as typed. */
export type PercentPair = {
	x: string,
	y: string,
};

export type PercentResult = 
/**  A field is empty: nothing to answer yet. */
{ kind: "empty" } | { kind: "answered"; 
/**  The numbers as read, for the formula written beside the result. */
x: string; y: string; exact: string; rounded: string } | 
/**  One-based, in characters of the field. */
{ kind: "unreadable"; field: Operand; at: number } | 
/**  A division by zero: a share of 0, or a percentage that brings a value to nothing. */
{ kind: "divisionByZero" } | 
/**  An evolution from 0 is no percentage. */
{ kind: "fromZero" } | { kind: "tooLarge" };

export type PercentagesAnswer = {
	of: PercentResult,
	share: PercentResult,
	change: PercentResult,
	apply: PercentResult,
	before: PercentResult,
};

export type PercentagesRequest = {
	/**  x % of y. */
	of: PercentPair,
	/**  x is what percentage of y. */
	share: PercentPair,
	/**  From x to y, by what percentage. */
	change: PercentPair,
	/**  y raised, or lowered, by x %. */
	apply: PercentPair,
	lower: boolean,
	/**  What y was before it moved by x %. */
	before: PercentPair,
	decimals: number,
};

export type PermissionsAnswer = {
	mode: ModeReading,
	umask: UmaskReading,
};

export type PermissionsRequest = {
	/**  `755`, `0644`, `4755`, `rwxr-xr-x`, `drwxr-xr-x`. */
	mode: string,
	umask: string,
};

/**  One item of a field's list. A day of the week is 0 (Sunday) to 7 (Sunday again). */
export type Piece = { kind: "every" } | { kind: "value"; value: number } | { kind: "range"; from: number; to: number } | 
/**  `*\/15`. */
{ kind: "step"; step: number } | 
/**  `9-18/2`, `5-59/10`. */
{ kind: "steppedRange"; step: number; from: number; to: number } | { kind: "lastDayOfMonth" } | 
/**  `15W`: the weekday nearest the 15th. */
{ kind: "nearestWeekday"; day: number } | 
/**  `5L`: the last Friday of the month. */
{ kind: "lastWeekday"; weekday: number } | 
/**  `1#2`: the second Monday of the month. */
{ kind: "nth"; weekday: number; nth: number };

export type Placeholder = {
	name: string,
	defaultValue: string,
	/**
	 *  A value gone orphan — its token renamed in the text — stays out of sight without
	 *  being erased.
	 */
	value: string,
};

export type PlanLine = { kind: "placed"; name: string; hosts: string; cidr: string; usable: string; first: string; last: string } | 
/**  What is left of the block is too small for it. */
{ kind: "noRoom"; name: string; hosts: string } | 
/**  No host count on that line. */
{ kind: "unreadable"; text: string };

/**
 *  Not sealed: SQL filters and sorts on it. Declared from the least to the most pressing,
 *  the order of the keys 0 to 4.
 */
export type Priority = "none" | "low" | "medium" | "high" | "urgent";

export type QrAnswer = { kind: "empty" } | { kind: "tooLong"; bytes: number; maximum: number } | { kind: "code"; payload: string; version: number; 
/**  Modules on a side, margin left out. */
modules: number; bytes: number; capacity: number; recoverable: number; 
/**  Modules on a side, margin included: the `viewBox` of `path`. */
side: number; 
/**  The dark modules as one SVG path, a rectangle per horizontal run. */
path: string; missingScheme: boolean };

export type QrContent = { kind: "text"; text: string } | { kind: "url"; url: string } | { kind: "wifi"; ssid: string; password: string; security: WifiSecurity; hidden: boolean } | { kind: "email"; to: string; subject: string; body: string } | { kind: "contact"; name: string; phone: string; email: string; organisation: string };

export type QrCorrection = "low" | "medium" | "quartile" | "high";

export type QrFormat = "svg" | "png";

export type QrRequest = {
	content: QrContent,
	correction: QrCorrection,
	margin: number,
};

export type QueryParameter = {
	name: string,
	value: string,
};

/**  What was drawn rather than stamped: the characters as pasted, and the bits they hold. */
export type RandomPart = {
	text: string,
	bits: number,
};

export type RateUnit = "bitPerSecond" | "kilobitPerSecond" | "megabitPerSecond" | "gigabitPerSecond" | "bytePerSecond" | "kilobytePerSecond" | "megabytePerSecond" | "gigabytePerSecond";

export type ReadAs = "unix" | "iso8601" | "weekDate" | "ordinalDate" | "rfc2822";

/**  What the File menu draws: the libraries, and which of them is open. */
export type Registry = {
	libraries: LibraryEntry[],
	open: string | null,
};

export type ReverseDns = 
/**  One address: the name its PTR record goes under. */
{ kind: "record"; name: string } | 
/**  The zones the block covers whole. */
{ kind: "zones"; first: string; last: string; count: number } | 
/**  Smaller than the zone it lies in: delegated through RFC 2317's aliases. */
{ kind: "classless"; zone: string };

/**
 *  One kept body, as the panel lists it.
 * 
 *  Metadata only: twenty bodies across the bridge to draw twenty dates would be the whole
 *  history.
 */
export type Revision = {
	id: string,
	takenAt: string,
	/**  So a row can say how much a version held without carrying it. */
	characters: number,
};

/**
 *  The French RIB's key, over the bank, the branch and the account, a letter of the account read
 *  as a digit (`A` and `J` as 1, `B`, `K` and `S` as 2…).
 */
export type RibKey = {
	given: string,
	expected: string,
};

export type Run = {
	date: string,
	time: string,
	/**  1 is Monday. */
	weekday: number,
	offset: string,
	epochMilliseconds: number | null,
};

/**
 *  One seeded note, and which of the seeded folders it lands in.
 * 
 *  An index into the folders the same command creates, which have no id yet. `None` stays
 *  loose, which the first launch shows on purpose.
 */
export type SampleNote = {
	folder?: number | null,
	draft: NoteDraft,
};

export type SavedBytes = { kind: "saved"; bytes: number } | { kind: "invalid" } | { kind: "failed"; problem: FileProblem };

export type SavedCode = { kind: "saved"; bytes: number } | { kind: "nothing" } | { kind: "failed"; problem: FileProblem };

/**
 *  No `Title` variant: a note found by its own title needs no excerpt, which would repeat the
 *  biggest thing on the card. That case is `SearchMatch::Title`.
 */
export type SearchField = "tag" | "body" | "item";

/**  What made a note match, and where. */
export type SearchHit = {
	field: SearchField,
	/**  The matching line, not the whole body: a card has room for one. */
	excerpt: string,
};

/**  Declared in the order the format sections run: snippets by language, then the other kinds. */
export type SectionGroup = { group: "language"; language: Language } | 
/**  A Note or a todo list, whose kind is its format. */
{ group: "kind"; kind: NoteKind } | { group: "priority"; priority: Priority };

export type Segment = "header" | "payload" | "signature";

/**  Three fields rather than a map, so a missing shortcut is a compile error. */
export type ShortcutBindings = {
	capture: string,
	newNote: string,
	palette: string,
};

/**  What one decimal unit is in the binary unit of the same rank: `1 GB = 0.931 GiB`. */
export type SizeGap = {
	decimal: SizeUnit,
	binary: SizeUnit,
	exact: string,
	rounded: string,
};

export type SizeRow = {
	unit: SizeUnit,
	exact: string,
	rounded: string,
};

export type SizeUnit = "bit" | "kilobit" | "megabit" | "gigabit" | "terabit" | "byte" | "kilobyte" | "megabyte" | "gigabyte" | "terabyte" | "petabyte" | "kibibyte" | "mebibyte" | "gibibyte" | "tebibyte" | "pebibyte";

export type SizesAnswer = { kind: "converted"; unit: SizeUnit; 
/**  The unit was written in the text, rather than chosen beside it. */
unitInText: boolean; rows: SizeRow[]; gap: SizeGap } | 
/**  One-based, in characters. */
{ kind: "unreadable"; at: number } | { kind: "negative"; at: number } | 
/**  Past the 28 digits exact arithmetic holds. */
{ kind: "tooLarge" };

export type SizesRequest = {
	/**  A number, with its unit or without one. */
	text: string,
	/**  The unit of a number typed without one. */
	unit: SizeUnit,
	/**  How many decimals the rounded values keep; the exact ones keep all. */
	decimals: number,
};

export type SlugOptions = {
	separator: SlugSeparator,
	lowercase: boolean,
};

export type SlugSeparator = "dash" | "underscore" | "dot";

export type SortDirection = "descending" | "ascending";

export type SortKey = "modified" | "created" | "priority" | 
/**  The kind, then the language. */
"format" | "title";

export type Space = {
	id: string,
	/**  Uniqueness is case-insensitive, decided by persistence. */
	name: string,
	/**  Hoisted to the head of the list, the way a pinned note is on the canvas. */
	pinned?: boolean,
};

export type SpaceDraft = {
	name: string,
};

/**
 *  Offsets in UTF-16 code units: the front's strings count in them, and "Voir dans le code"
 *  puts a caret with one.
 */
export type Span = {
	start: number,
	end: number,
};

export type SpanKind = "plain" | "strong" | "code";

export type StatsRequest = {
	text: string,
	/**  `A` and `a` counted as one. */
	foldCase: boolean,
	countWhitespace: boolean,
};

export type Strength = "veryWeak" | "weak" | "fair" | "strong" | "veryStrong";

export type Subnet = {
	cidr: string,
	usable: string,
};

export type TagUsage = {
	tag: string,
	noteCount: number,
};

export type TextCase = "camel" | "pascal" | "snake" | "kebab" | "constant" | "title" | "sentence" | "dot" | "path" | "train" | "lower" | "upper" | "flat";

export type TextDiffAnswer = {
	/**  In the unit asked: lines, words or characters. */
	added: number,
	removed: number,
	rows: TextDiffRow[],
	rowsTruncated: boolean,
	/**  From A to B, three lines of context, as `diff -u` writes it. */
	unified: string,
	identical: boolean,
	/**  Both sides are JSON: they can be compared as values instead. */
	bothJson: boolean,
};

export type TextDiffLine = {
	/**  One-based, in that side's own text. */
	number: number,
	pieces: TextPiece[],
};

export type TextDiffRequest = {
	a: string,
	b: string,
	granularity: Granularity,
	ignoreTrailingWhitespace: boolean,
	ignoreAllWhitespace: boolean,
	ignoreCase: boolean,
	/**  CRLF against LF is the commonest difference nobody meant. */
	ignoreLineEndings: boolean,
};

/**  One row of the side-by-side view: a side without a line is a gap. */
export type TextDiffRow = {
	kind: TextRowKind,
	left: TextDiffLine | null,
	right: TextDiffLine | null,
};

/**  A piece of a line, marked when it is what changed. */
export type TextPiece = {
	text: string,
	changed: boolean,
};

export type TextRowKind = "same" | "added" | "removed" | "modified";

export type TextSizes = {
	normal: boolean,
	large: boolean,
};

export type TextStats = {
	/**  As a reader counts them: `é` written as `e` and an accent is one, and so is a flag. */
	characters: number,
	codePoints: number,
	/**  What JavaScript's `length` counts, and many a field limit. */
	utf16Units: number,
	utf8Bytes: number,
	nonWhitespace: number,
	words: number,
	lines: number,
	nonEmptyLines: number,
	paragraphs: number,
	distinct: number,
	frequencies: Frequency[],
	frequenciesTruncated: boolean,
};

export type TitleLanguage = 
/**  Every word capitalised. */
"english" | 
/**  The small words stay in lower case, but at the start. */
"french";

export type TokenState = "valid" | "expired" | "notYetValid" | 
/**  Neither `exp` nor `nbf`: nothing to be valid against. */
"undated";

export type TransferAnswer = { kind: "estimated"; 
/**  At the rate typed, slowed by the efficiency. */
estimate: TransferTime; 
/**  At the full rate. */
theoretical: TransferTime; 
/**  The efficiency used, once held within its bounds. */
efficiency: number; 
/**  Fastest first, the rate typed among the common ones. */
connections: ConnectionEstimate[] } | 
/**  One-based, in characters. */
{ kind: "unreadable"; field: TransferField; at: number } | { kind: "negative"; field: TransferField; at: number } | 
/**  A rate of nothing carries nothing, ever. */
{ kind: "zeroRate" } | 
/**  Past the 28 digits exact arithmetic holds. */
{ kind: "tooLarge" };

export type TransferField = "size" | "rate";

export type TransferRequest = {
	/**  A quantity, with its unit or without one. */
	size: string,
	/**  The unit of a quantity typed without one. */
	sizeUnit: SizeUnit,
	rate: string,
	rateUnit: RateUnit,
	/**  The share of the rate a link really carries, in percent; held between 50 and 100. */
	efficiency: number,
};

/**  A length of time to the nearest second, for the front to spell. Past a year it stays in days. */
export type TransferTime = {
	days: number,
	hours: number,
	minutes: number,
	seconds: number,
	/**  More than nothing, but less than half a second. */
	underASecond: boolean,
};

/**  The two counts part when the zone's offset differs at either end: a daylight-saving change. */
export type Transition = {
	/**  The local date the clocks changed on — the last change, when there were several. */
	date: string | null,
	/**  The clocks went forward, to summer time. */
	forward: boolean,
	/**  The calendar's count less the clock's. */
	minutes: number,
	/**  The wall clock's total, beside `Elapsed::total_minutes`. */
	wallMinutes: number,
};

export type TrashedNote = {
	deletedAt: string,
	/**  Derived, never stored: retention can change between versions. */
	purgeAt: string,
} & Note;

/**  Labels cross already translated: the interface language is a front-end preference. */
export type TrayLabels = {
	open: string,
	newNote: string,
	capture: string,
	palette: string,
	quit: string,
};

export type UmaskReading = { kind: "empty" } | { kind: "read"; file: Mode; directory: Mode } | { kind: "refused"; problem: ModeProblem; at: number };

export type Unsupported = {
	keyword: string,
	/**  A `JSONPath` into the schema. */
	path: string,
};

export type UrlAnswer = { kind: "parsed"; parts: UrlParts } | { kind: "invalid"; problem: UrlProblem };

export type UrlCodecAnswer = { kind: "done"; text: string } | 
/**  `at` counts characters: a `%` without two hexadecimal digits after it. */
{ kind: "malformedEscape"; at: number } | 
/**  The escapes are well formed, but the bytes they spell are no UTF-8 text. */
{ kind: "notUtf8" };

export type UrlCodecRequest = {
	text: string,
	direction: CodecDirection,
	scope: UrlScope,
};

/**  The user and the password decoded, the path as written, the query both ways. */
export type UrlParts = {
	scheme: string,
	username: string | null,
	password: string | null,
	host: string | null,
	/**  The port written, or the scheme's own when none is. */
	port: number | null,
	portIsDefault: boolean,
	path: string,
	query: string | null,
	parameters: QueryParameter[],
	fragment: string | null,
};

export type UrlProblem = "empty" | 
/**  "example.com/path": a URL starts with its scheme. */
"noScheme" | "emptyHost" | "invalidPort" | "invalidAddress" | "invalidDomain" | "other";

export type UrlScope = 
/**  One value of a query or of a path: its `/`, `?` and `&` are escaped too. */
"component" | 
/**  A URL as a whole, whose structure stays readable. */
"whole";

export type UuidVariant = "ncs" | 
/**  RFC 9562, which every UUID made today follows. */
"rfc" | "microsoft" | "future";

/**  What a value was, as the list of changes shows it: itself when short, its size otherwise. */
export type ValueSummary = { kind: "scalar"; text: string } | { kind: "object"; keys: number } | { kind: "array"; items: number };

/**  What the front end renders before it renders anything else. */
export type VaultState = 
/**
 *  A library that has never been encrypted: the first launch asks for a passphrase
 *  twice and creates one.
 */
"absent" | 
/**  A key file is there and the passphrase has not been given yet. */
"locked" | 
/**
 *  Held in Rust, not in the front end: a page reload must not ask again for a library
 *  this process has open.
 */
"unlocked" | 
/**
 *  ⚠️ A database is here and its key file is not. Not `Absent`: a new key over it would
 *  open nothing it holds, and asking for a new phrase would be the first step towards that.
 */
"keyMissing";

export type Verification = 
/**  No secret typed. */
"notAsked" | "valid" | "invalid" | 
/**  RS*, PS*, ES*, `EdDSA`: named, not verified here. */
"notVerifiedHere" | "unsigned" | 
/**  A secret said to be base64 that is not. */
"unreadableSecret";

export type WcagLevel = 
/**  4.5:1 for body text. */
"aa" | 
/**  7:1 for body text. */
"aaa";

/**  The first character UTF-8 writes in more than one byte: « é » takes 2. */
export type WideCharacter = {
	character: string,
	bytes: number,
};

export type WifiSecurity = "wpa" | "wep" | "open";

/**  Pushed from the preferences panel as it changes, like the tray labels. */
export type WindowBehavior = {
	closeToTray: boolean,
	minimizeToTray: boolean,
};

export type ZoneEntry = {
	zone: string,
	city: string,
	offset: string,
	abbreviation: string | null,
};

/**  One zone that moved. A batch of these is what a gesture eventually writes. */
export type ZonePlacement = {
	folderId: string,
	frame: BoardFrame,
};

export type ZoneReading = {
	offset: string,
	abbreviation: string | null,
	isoUtc: string,
};

export type ZoneTime = {
	zone: string,
	city: string,
	local: boolean,
	/**  The zone the time was typed in. */
	source: boolean,
	date: string,
	time: string,
	iso: string,
	offset: string,
	abbreviation: string | null,
	summerTime: boolean,
	/**  Days ahead of (or behind) the date typed: `1` in Tokyo for an evening in Paris. */
	dayShift: number,
};

export type ZonesAnswer = { kind: "placed"; from: string; 
/**  Both readings of a time the clocks went through twice, the earlier first. */
ambiguous: [ZoneReading, ZoneReading] | null; times: ZoneTime[]; unknown: string[] } | 
/**  The clocks jumped over it, from one offset to the other. */
{ kind: "skipped"; from: string; before: string; after: string } | 
/**  One-based, in characters. */
{ kind: "unreadable"; at: number } | { kind: "outOfRange" } | { kind: "unknownZone"; zone: string };

export type ZonesRequest = {
	/**  A date and time on the wall clock of `from`, or an instant that carries its offset. */
	text: string,
	/**  `None` is this machine's zone. */
	from: string | null,
	zones: string[],
	/**  For a time the clocks went through twice: the second pass rather than the first. */
	later: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

