// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  No command returns the raw list: it would invite re-filtering on the front end. */
	queryNotes: (query: NotesQuery) => typedError<NotesView, AppError>(__TAURI_INVOKE("query_notes", { query })),
	/**
	 *  The whole note. A list sends previews ([`DisplayNote::truncated`]), so the editor and
	 *  every copy of a long body read it here.
	 */
	getNote: (id: string) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("get_note", { id })),
	createNote: (draft: NoteDraft) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("create_note", { draft })),
	/**
	 *  The first launch: the space, its folders and the notes in one transaction, since a space
	 *  standing alone reads as "already seeded" for good. The strings stay on the front end, with
	 *  the translations. Answers the space it made, which the front end opens on.
	 */
	seedSamples: (spaceName: string, folders: string[], notes: SampleNote[]) => typedError<Space, AppError>(__TAURI_INVOKE("seed_samples", { spaceName, folders, notes })),
	updateNote: (id: string, patch: NotePatch) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("update_note", { id, patch })),
	/**
	 *  The bodies kept beside a note, newest first.
	 * 
	 *  Instants and sizes, never the bodies.
	 */
	listRevisions: (id: string) => typedError<Revision[], AppError>(__TAURI_INVOKE("list_revisions", { id })),
	/**  What going back to a kept body would change, line by line, against the current text. */
	revisionDiff: (id: string, revisionId: string) => typedError<DiffLine[], AppError>(__TAURI_INVOKE("revision_diff", { id, revisionId })),
	/**
	 *  Goes back to a kept body, dropping it and every body kept after it from the history.
	 * 
	 *  Leaves `updated_at` alone: putting something back is not editing it.
	 */
	restoreRevision: (id: string, revisionId: string) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("restore_revision", { id, revisionId })),
	/**
	 *  Moves to the trash: the note comes back through [`restore_notes`] for
	 *  [`trash::RETENTION`].
	 */
	deleteNote: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note", { id })),
	deleteNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_notes", { ids })),
	restoreNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("restore_notes", { ids })),
	/**  Purges first: the trash must never show a note a restart would erase. */
	listTrash: () => typedError<TrashedNote[], AppError>(__TAURI_INVOKE("list_trash")),
	purgeNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("purge_notes", { ids })),
	emptyTrash: () => typedError<number, AppError>(__TAURI_INVOKE("empty_trash")),
	moveNotes: (ids: string[], spaceId: string) => typedError<NotePlacement[], AppError>(__TAURI_INVOKE("move_notes", { ids, spaceId })),
	/**  The undo of [`move_notes`]: each note goes back to the space it left. */
	moveNotesBack: (placements: NotePlacement[]) => typedError<number, AppError>(__TAURI_INVOKE("move_notes_back", { placements })),
	/**  Normalized here as everywhere else, or a typed `#urgent` would not join `urgent`. */
	tagNotes: (ids: string[], tags: string[]) => typedError<NoteTag[], AppError>(__TAURI_INVOKE("tag_notes", { ids, tags })),
	/**  The undo of [`tag_notes`]: exactly the pairs it added, and nothing wider. */
	untagNotes: (pairs: NoteTag[]) => typedError<number, AppError>(__TAURI_INVOKE("untag_notes", { pairs })),
	/**  What a corpus-wide tag action is about to touch, asked before it runs. */
	countNotesTagged: (tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("count_notes_tagged", { tags })),
	listTags: () => typedError<TagUsage[], AppError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Renames one tag or merges several: renaming onto an existing tag is a merge anyway,
	 *  since a note cannot carry one twice.
	 */
	renameTags: (tags: string[], into: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_tags", { tags, into })),
	/**  A list rather than one tag at a time: one round trip per tag is one lock per tag. */
	deleteTags: (tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_tags", { tags })),
	/**
	 *  No note identifier: the palette fills an unsaved draft as readily as a saved note.
	 *  The database is read only for the global variables.
	 */
	fillPlaceholders: (content: string, values: { [key in string]: string }) => typedError<string, AppError>(__TAURI_INVOKE("fill_placeholders", { content, values })),
	/**
	 *  A command of its own rather than a `NotePatch` field, so `updated_at` stays put: filling a
	 *  field is not editing the note.
	 */
	setPlaceholderValues: (id: string, values: { [key in string]: string }) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("set_placeholder_values", { id, values })),
	listGlobalPlaceholders: () => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("list_global_placeholders")),
	/**  Stores the whole set: what is not sent is what the user removed. */
	setGlobalPlaceholders: (values: { [key in string]: string }) => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("set_global_placeholders", { values })),
	/**  `None` = every space, like [`crate::notes::view::NotesQuery::space_id`]. */
	listFolders: (spaceId: string | null) => typedError<Folder[], AppError>(__TAURI_INVOKE("list_folders", { spaceId })),
	/**
	 *  The second way to look at a space: folders as zones, their notes inside, the loose ones
	 *  beside them. It reads the whole space and marks what matches rather than narrowing, and
	 *  draws no folder chips — a chip naming the zone a card sits in is noise.
	 */
	boardView: (query: BoardQuery) => typedError<BoardView, AppError>(__TAURI_INVOKE("board_view", { query })),
	/**
	 *  Where the zones and the loose cards ended up, as one batch and one transaction: a gesture
	 *  cut short must not leave half a board. Filing is not here (see [`file_notes`]). This is
	 *  also the undo of [`arrange_board`], with the layout that one answered.
	 */
	saveBoardLayout: (zones: ZonePlacement[], cards: CardPlacement[]) => typedError<null, AppError>(__TAURI_INVOKE("save_board_layout", { zones, cards })),
	/**
	 *  Puts one space's board back in order, as far as `scope` allows, and answers the layout it
	 *  replaced: the only moment the old one still exists, for an undo.
	 */
	arrangeBoard: (spaceId: string, scope: BoardScope) => typedError<BoardArrangement, AppError>(__TAURI_INVOKE("arrange_board", { spaceId, scope })),
	createFolder: (draft: FolderDraft) => typedError<Folder, AppError>(__TAURI_INVOKE("create_folder", { draft })),
	renameFolder: (id: string, name: string) => typedError<Folder, AppError>(__TAURI_INVOKE("rename_folder", { id, name })),
	recolourFolder: (id: string, colour: FolderColour) => typedError<Folder, AppError>(__TAURI_INVOKE("recolour_folder", { id, colour })),
	/**
	 *  No refuge, unlike [`crate::spaces::delete_space`]: the notes come out loose, a legitimate
	 *  state.
	 */
	deleteFolder: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_folder", { id })),
	/**
	 *  A batch, like [`crate::notes::move_notes`]: the selection bar files a whole selection,
	 *  and a drop on the board is a batch of one. `folderId` absent unfiles.
	 */
	fileNotes: (ids: string[], folderId: string | null) => typedError<NoteFiling[], AppError>(__TAURI_INVOKE("file_notes", { ids, folderId })),
	/**  The undo of [`file_notes`]: each note goes back to the folder it left, or to loose. */
	fileNotesBack: (filings: NoteFiling[]) => typedError<number, AppError>(__TAURI_INVOKE("file_notes_back", { filings })),
	listSpaces: () => typedError<Space[], AppError>(__TAURI_INVOKE("list_spaces")),
	createSpace: (draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("create_space", { draft })),
	renameSpace: (id: string, draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("rename_space", { id, draft })),
	pinSpace: (id: string, pinned: boolean) => typedError<Space, AppError>(__TAURI_INVOKE("pin_space", { id, pinned })),
	deleteSpace: (id: string, targetSpaceId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_space", { id, targetSpaceId })),
	/**
	 *  ⚠️ `path` is not checked, and cannot be: it is the native picker's answer. With
	 *  `read_attachment` this reads any file the account can read into the `WebView`, and what keeps
	 *  that harmless is the CSP — `script-src 'self'`, nothing remote — not this function.
	 */
	attachFile: (noteId: string, path: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_file", { noteId, path })),
	/**  The bytes do not cross the bridge: the clipboard is read natively, as raw RGBA. */
	attachClipboardImage: (noteId: string, fileName: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_clipboard_image", { noteId, fileName })),
	listAttachments: (noteId: string) => typedError<Attachment[], AppError>(__TAURI_INVOKE("list_attachments", { noteId })),
	readAttachment: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("read_attachment", { id })),
	/**
	 *  The call starts from Rust: opening a path from the front end would mean allowing
	 *  `opener:allow-open-path` over a whole directory.
	 * 
	 *  ⚠️ The one place a decrypted copy reaches the disk: the program the desktop picks reads a
	 *  path. It goes under the profile's `open/` ([`sealed::plaintext_directory`]) and is swept
	 *  on exit and at the next launch, since that program may still hold it on close.
	 */
	openAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_attachment", { id })),
	/**  The path comes from a native picker; the write stays here. */
	saveAttachment: (id: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("save_attachment", { id, path })),
	deleteAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_attachment", { id })),
	/**
	 *  A `None` passphrase writes the file in the clear: the library's key protects what is
	 *  on this machine, never what leaves it.
	 */
	exportNotes: (path: string, scope: ExportScope, passphrase: string | null) => typedError<ExportReport, AppError>(__TAURI_INVOKE("export_notes", { path, scope, passphrase })),
	/**
	 *  The file is read before the lock is taken: parsing a large export while holding the
	 *  connection would block every other command for the length of it.
	 */
	importNotes: (path: string, passphrase: string | null) => typedError<ImportReport, AppError>(__TAURI_INVOKE("import_notes", { path, passphrase })),
	/**  Nothing is sent anywhere: "share" stops at the clipboard. */
	shareNotes: (ids: string[]) => typedError<string, AppError>(__TAURI_INVOKE("share_notes", { ids })),
	/**  Whether an import will want a phrase, so the interface can ask before it starts. */
	exportIsProtected: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("export_is_protected", { path })),
	vaultState: () => typedError<VaultState, AppError>(__TAURI_INVOKE("vault_state")),
	/**
	 *  The first launch. Refuses a library that already has a key file: that file is the only
	 *  way into the notes beside it.
	 */
	createVault: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("create_vault", { passphrase })),
	/**
	 *  `(async)` because deriving the key is slow on purpose, and would freeze the window over
	 *  every attempt on the main thread.
	 */
	unlockVault: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("unlock_vault", { passphrase })),
	/**
	 *  A new phrase over the same library, from the preferences panel.
	 * 
	 *  Not a re-encryption: the key the notes are sealed with is rewrapped, and the library stays
	 *  open on it.
	 */
	changePassphrase: (current: string, next: string) => typedError<PassphraseChange, AppError>(__TAURI_INVOKE("change_passphrase", { current, next })),
	/**
	 *  Sets the damaged library aside so the next unlock starts on a fresh one.
	 * 
	 *  Answers the folder it moved everything into, so the interface can say where.
	 */
	setAsideDamagedLibrary: () => typedError<string, AppError>(__TAURI_INVOKE("set_aside_damaged_library")),
	/**
	 *  Archives a library whose passphrase was forgotten, so a fresh one can be started.
	 * 
	 *  Nothing is recovered: the notes leave sealed, under the forgotten phrase, and `vault.json`
	 *  goes with them for the day the phrase comes back.
	 */
	archiveLockedLibrary: () => typedError<string, AppError>(__TAURI_INVOKE("archive_locked_library")),
	/**  The copies that exist, newest first, for the panel that lists them. */
	listBackups: () => typedError<Backup[], AppError>(__TAURI_INVOKE("list_backups")),
	/**
	 *  Puts a copy back, and answers where the library it replaced was moved to.
	 * 
	 *  ⚠️ Closes the library first, under the lock every command takes: renaming a database out
	 *  from under a live connection loses it. Every command then answers `Locked`, which sends
	 *  the interface back to the gate to ask for the restored copy's phrase.
	 */
	restoreBackup: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("restore_backup", { id })),
	/**  The libraries, and which one is open. */
	listLibraries: () => typedError<Registry, AppError>(__TAURI_INVOKE("list_libraries")),
	/**  Adds one, and leaves it closed: opening it is a second, deliberate gesture. */
	createLibrary: (name: string) => typedError<LibraryEntry, AppError>(__TAURI_INVOKE("create_library", { name })),
	/**
	 *  Closes whatever is open and points the registry at another one.
	 * 
	 *  ⚠️ The connection `Mutex` is emptied under the lock every command takes: they all answer
	 *  `Locked` afterwards, which sends the interface back to the gate for the other passphrase.
	 */
	openLibrary: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_library", { id })),
	renameLibrary: (id: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_library", { id, name })),
	/**
	 *  Erases a library and everything in it.
	 * 
	 *  Refused on the open one: deleting files under a live connection takes the process down.
	 */
	deleteLibrary: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_library", { id })),
	appChangelog: () => __TAURI_INVOKE<ChangelogRelease[]>("app_changelog"),
	/**
	 *  Replaces only the menu when the tray exists, so a language change does not flicker. No
	 *  `Result`: without a tray, `tray_exists` is what stops closing from hiding the window.
	 */
	syncTray: (labels: TrayLabels) => __TAURI_INVOKE<void>("sync_tray", { labels }),
	/**  The native side can only fail silently, and a log line is not an interface. */
	setGlobalShortcuts: (bindings: ShortcutBindings) => __TAURI_INVOKE<string[]>("set_global_shortcuts", { bindings }),
	setWindowBehavior: (behavior: WindowBehavior) => __TAURI_INVOKE<void>("set_window_behavior", { behavior }),
};

/* Constants */
export const APP_METADATA = {"author":"Valentin MILLET","authorHandle":"@vmillet-dev","name":"DevNotes","repository":"https://github.com/vmillet-dev/devnotes-rs","rustVersion":"1.97.1"} as const;

export const AUTOMATIC_BACKUPS_KEY = "devnotes.automaticBackups" as const;

export const DEFAULT_SHORTCUTS = {"capture":"Ctrl+Alt+V","newNote":"Ctrl+Alt+N","palette":"Ctrl+Alt+P"} as const;

export const FIELD_NAME_PATTERN = "^[A-Za-z0-9_-]+$" as const;

export const GLOBAL_ACTION_EVENT = "devnotes:action" as const;

export const PREFERENCES_FILE = "preferences.json" as const;

/* Types */
export type AppError = {
	code: ErrorCode,
	/**  Values to interpolate into the translated message, e.g. `{ "name": "Personal" }`. */
	params: { [key in string]: string },
	detail: string,
};

export type Attachment = {
	id: string,
	noteId: string,
	/**  The original name, the one displayed. Never used as a path. */
	fileName: string,
	mimeType: string,
	/**  `u32` and not `u64`: Specta refuses what JSON cannot carry without loss. */
	byteSize: number,
	createdAt: string,
};

/**
 *  One copy, as the interface lists it. `bytes` is `f64` because specta refuses the integer
 *  types JSON cannot carry exactly.
 */
export type Backup = {
	/**  The folder's name, which is its stamp, and what a restore asks for. */
	id: string,
	takenAt: string,
	bytes: number | null,
	/**  Whether the key file travelled with it: without one, restoring loses the library. */
	openable: boolean,
};

/**  What a tidy-up did, and what it takes to walk it back. */
export type BoardArrangement = {
	/**  What actually moved: a board already in order moves nothing, and opens no undo. */
	moved: number,
	previous: BoardLayout,
};

export type BoardFrame = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**
 *  A whole board's geometry: every zone's frame and every loose card's place. What a tidy-up
 *  writes, and, read back first, what its undo puts back.
 */
export type BoardLayout = {
	zones: ZonePlacement[],
	cards: CardPlacement[],
};

/**  `flatten`: the front end draws this with the same card component the canvas uses. */
export type BoardNote = {
	/**
	 *  Dimmed in place rather than reflowed: spatial memory is what the board has that the
	 *  date view does not.
	 */
	matches: boolean,
	/**  `None` inside a zone, where a card flows; `Some` only on the free background. */
	position: BoardPoint | null,
} & DisplayNote;

export type BoardPoint = {
	x: number,
	y: number,
};

export type BoardQuery = {
	/**  Required, unlike `NotesQuery::space_id`: a board across every space has no zones. */
	spaceId: string,
	search: string,
	filter: NoteFilter,
	tags: string[],
	languages: Language[],
	now: string,
};

/**
 *  How much of a board a tidy-up is allowed to move.
 * 
 *  Two scopes rather than one with a warning: what goes to pieces is the loose cards, and a
 *  zone placed and sized by hand is the only manual work the board holds.
 */
export type BoardScope = 
/**  The loose cards alone, flowed under the zones as they stand. */
"looseCards" | 
/**
 *  The zones as well: reading order, sized to their contents. Overwrites every frame
 *  set by hand.
 */
"everything";

export type BoardView = {
	zones: BoardZone[],
	loose: BoardNote[],
	/**
	 *  The space's, like `NotesView`'s: facets drawn from filtered notes would empty the
	 *  rails on the first selection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	isFiltering: boolean,
	matched: number,
	/**  The surface to pan over, sized from what is on it. */
	width: number,
	height: number,
};

export type BoardZone = {
	folder: Folder,
	frame: BoardFrame,
	notes: BoardNote[],
};

/**
 *  One loose card that moved. Filing is not here: it goes through `file_notes`, whose answer
 *  the undo puts back. A position has no undo of its own.
 */
export type CardPlacement = {
	noteId: string,
	position: BoardPoint,
};

export type ChangelogRelease = {
	/**  `0.1.1`, or whatever the heading names. Square brackets are dropped. */
	version: string,
	/**  `None` when the heading carries no date; never invented. */
	date: string | null,
	sections: ChangelogSection[],
};

/**  One `### ` heading, or the anonymous one a release with no category gets.        */
export type ChangelogSection = {
	/**  Empty for that anonymous category: the front then renders no heading. */
	title: string,
	items: ChangelogSpan[][],
};

export type ChangelogSpan = {
	kind: SpanKind,
	text: string,
};

/**
 *  No identifier: the position is the identity — `note_items` is keyed on
 *  `(note_id, position)`, and a write rewrites the whole list.
 */
export type ChecklistItem = {
	text: string,
	done: boolean,
};

/**  One line of a kept body, compared with the text restoring it would replace. */
export type DiffLine = 
/**  In both: restoring leaves it where it is. */
{ kind: "kept"; text: string } | 
/**  Only in the kept body: restoring brings it back. */
{ kind: "restored"; text: string } | 
/**  Only in the current text: restoring takes it away. */
{ kind: "dropped"; text: string } | 
/**  Unchanged lines too far from any change to be worth reading. */
{ kind: "skipped"; count: number };

/**  `flatten`: the front end has a single note type. */
export type DisplayNote = {
	footer: NoteFooter,
	expiringSoon: boolean,
	/**  The list is derived from the text; the values are persisted. */
	placeholders: Placeholder[],
	/**  Filled in afterwards by whoever holds a connection: `decorate` reads no database. */
	attachmentCount: number,
	/**
	 *  Resolved in a pass of its own, like [`Self::attachment_count`]: the front end
	 *  never joins a `folder_id` against a list it happens to hold.
	 */
	folder: NoteFolder | null,
	/**
	 *  What copying yields when that is not the content, so `checklist::to_markdown` stays
	 *  the only place the `- [x] ` syntax exists.
	 */
	copyText: string | null,
	/**
	 *  Filled in afterwards by `view::build`; `None` outside a search, and for a note
	 *  found by its own title.
	 */
	searchHit: SearchHit | null,
	/**  `content` holds only its first lines: a list sends previews, `get_note` the body. */
	truncated: boolean,
} & Note;

/**
 *  ⚠️ A new variant breaks the front-end build until `CODE_KEYS`
 *  (`core/services/errors/error-notifier.service.ts`) and both locales have its key.
 */
export type ErrorCode = "noteNotFound" | "spaceNotFound" | "duplicateSpaceName" | "folderNotFound" | "duplicateFolderName" | "attachmentNotFound" | "revisionNotFound" | "libraryNotFound" | "libraryOpen" | "lastLibrary" | "nothingToSetAside" | "backupNotFound" | "backupUnopenable" | "fileAccess" | "importFormat" | 
/**  The `field` parameter names the offending field. */
"invalidInput" | 
/**  Poisoned mutex: a command panicked while holding the connection. */
"storageUnavailable" | 
/**  The unlock screen clears the field on this one rather than showing a banner. */
"wrongPassphrase" | 
/**  A command ran before the library was unlocked. */
"locked" | 
/**  The import needs the phrase the export was protected with. */
"passphraseRequired" | 
/**  SQLite says the file is corrupt: the one code the interface answers with an action. */
"libraryDamaged" | "storage";

export type ExportReport = {
	notes: number,
	spaces: number,
	folders: number,
	/**  What went into the archive; a record whose file is missing is left out. */
	attachments: number,
	/**  `false` means readable by anyone who has the file: the interface says which it wrote. */
	protected: boolean,
};

/**  What an export takes. */
export type ExportScope = { kind: "library" } | { kind: "space"; spaceId: string } | 
/**  A selection: the ids the canvas had ticked. */
{ kind: "notes"; ids: string[] };

export type Folder = {
	id: string,
	spaceId: string,
	/**  Uniqueness is case-insensitive inside its space, decided by persistence. */
	name: string,
	colour?: FolderColour,
	createdAt: string,
};

/**
 *  Assigned on creation, changed from the zone menu after: drawing a folder stays one
 *  gesture. The five are the theme's accents, each with a light-theme twin.
 */
export type FolderColour = "blue" | "amber" | "purple" | "green" | "red";

export type FolderDraft = {
	spaceId: string,
	name: string,
};

/**
 *  One event carrying a closed value rather than a topic per action: a mistyped topic is
 *  a silently inert subscription, and a new variant here stops the front compiling.
 */
export type GlobalAction = "capture" | "new-note" | "palette" | "quit";

/**  `skipped`: notes already present or whose space is missing, so an import can be replayed. */
export type ImportReport = {
	spacesCreated: number,
	/**  Matched by name inside the destination space, created when absent. */
	foldersCreated: number,
	notesImported: number,
	notesSkipped: number,
	/**
	 *  Brought down to the default for a `language` or `kind` this build does not know, and
	 *  counted so the loss is said.
	 */
	notesDegraded: number,
	attachmentsImported: number,
	/**
	 *  Records the archive named but did not carry: the only thing that says why a thumbnail
	 *  will never load.
	 */
	attachmentsMissing: number,
};

/**
 *  Closed: the front receives a generated union, so an unknown value stops compiling
 *  there instead of being refused at runtime.
 */
export type Language = "json" | "js" | "ts" | "py" | "rs" | "go" | "java" | "cs" | "php" | "c" | "sql" | "yml" | "toml" | "xml" | "html" | "css" | "sh" | "md" | 
/**  Default, and the signal that the front end chose nothing. */
"txt";

/**  One library, as the interface lists it. */
export type LibraryEntry = {
	id: string,
	name: string,
	/**  Relative to the profile, so a profile copied to another machine still resolves. */
	directory: string,
	createdAt: string,
};

export type Note = {
	id: string,
	spaceId: string,
	/**
	 *  The folder travels with an export; where its zone sits must never join this model,
	 *  which `transfer::Bundle` deserialises.
	 */
	folderId?: string | null,
	title: string,
	language: Language,
	content: string,
	/**  Breadcrumb, e.g. "API Gateway / Auth". Can be empty. */
	source: string,
	tags: string[],
	pinned: boolean,
	createdAt: string,
	updatedAt: string,
	lifecycle: NoteLifecycle,
	/**
	 *  `default`: `transfer::Bundle` deserialises `Note`, and export files from before todo
	 *  lists carry no such key.
	 */
	kind?: NoteKind,
	/**  A checklist has these instead of `content`. */
	items?: ChecklistItem[],
	/**  Written by `set_placeholder_values` alone, which leaves `updated_at` alone. */
	placeholderValues?: { [key in string]: string },
};

export type NoteDraft = {
	spaceId: string,
	/**  Set by the two places that file a new note: the board and the inside of a folder. */
	folderId?: string | null,
	title: string,
	language: Language,
	content: string,
	source: string,
	tags: string[],
	pinned: boolean,
	lifecycle: NoteLifecycle,
	kind?: NoteKind,
	items?: ChecklistItem[],
};

/**  Which folder each note left, the only thing that can put a filing back; `None` was loose. */
export type NoteFiling = {
	noteId: string,
	folderId?: string | null,
};

/**  `Untriaged` = notes with a deadline, those whose fate is not decided. */
export type NoteFilter = "all" | "pinned" | "untriaged";

/**
 *  What a card shows, resolved by the back end: the front end never joins an id against
 *  a list it happens to hold.
 */
export type NoteFolder = {
	id: string,
	name: string,
	colour: FolderColour,
};

/**
 *  The decision, not the rendering: the dated variants carry a date and not a label,
 *  so "4 min ago" ages on screen without a round trip.
 */
export type NoteFooter = { kind: "source"; value: string } | { kind: "expiry"; at: string } | { kind: "age"; at: string };

/**
 *  Closed, like `Language`: the front receives a generated union, so an unknown
 *  value stops compiling there.
 */
export type NoteKind = 
/**  Default, and what every note written before todo lists reads back as. */
"snippet" | "checklist";

export type NoteLifecycle = { kind: "permanent" } | { kind: "expires"; at: string };

/**
 *  ⚠️ A field set to `None` stays unchanged, and `#[specta(optional)]` makes the key omissible
 *  in TypeScript: without it the front sends `null` for what it does not touch, overwriting it.
 */
export type NotePatch = {
	spaceId?: string | null,
	title?: string | null,
	language?: Language | null,
	content?: string | null,
	source?: string | null,
	tags?: string[] | null,
	pinned?: boolean | null,
	lifecycle?: NoteLifecycle | null,
	kind?: NoteKind | null,
	/**  Replaces the whole list, like `tags`: a position is all the identity an item has. */
	items?: ChecklistItem[] | null,
};

/**  Where a note sat before a batch moved it — the only thing that can put it back. */
export type NotePlacement = {
	noteId: string,
	spaceId: string,
};

export type NoteSection = {
	key: NoteSectionKey,
	hasExpiringNotes: boolean,
	notes: DisplayNote[],
	showCreateGhost: boolean,
};

/**  A translation key on the front-end side: no readable label crosses the bridge. */
export type NoteSectionKey = "pinned" | "today" | "week" | "older" | "results";

/**
 *  One tag on one note: a batch answers pair by pair, so its undo cannot strip a tag the note
 *  already carried.
 */
export type NoteTag = {
	noteId: string,
	tag: string,
};

export type NotesQuery = {
	/**  `None` = every space: a choice, not an absence of one. */
	spaceId: string | null,
	/**
	 *  `None` = every folder, filed or not. No "unfiled" filter: the absence of a chip already
	 *  says it.
	 */
	folderId?: string | null,
	search: string,
	filter: NoteFilter,
	/**  A note passes if it carries at least one of these tags. */
	tags: string[],
	languages: Language[],
	now: string,
	/**
	 *  `Date#getTimezoneOffset()`, whose sign is the opposite of the offset (−120 for
	 *  UTC+2). Sections reason in local days.
	 */
	tzOffsetMinutes: number,
	/**  Their own section when the view is chronological, the head of the list when flat. */
	pinnedFirst: boolean,
};

export type NotesView = {
	sections: NoteSection[],
	/**
	 *  The space's, not the current filter's: facets drawn from filtered notes would empty
	 *  the rail on the first selection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	isFiltering: boolean,
	/**  `u32` and not `usize`: Specta refuses what JSON cannot carry exactly. */
	matched: number,
};

/**
 *  What a change reached. `backupsLeft` is the honest half: a key file copied somewhere else
 *  still opens with the retired phrase.
 */
export type PassphraseChange = {
	backupsRewrapped: number,
	backupsLeft: number,
};

export type Placeholder = {
	name: string,
	defaultValue: string,
	/**
	 *  A value gone orphan — its token renamed in the text — stays out of sight without
	 *  being erased.
	 */
	value: string,
};

/**  What the File menu draws: the libraries, and which of them is open. */
export type Registry = {
	libraries: LibraryEntry[],
	open: string | null,
};

/**
 *  One kept body, as the panel lists it.
 * 
 *  Metadata only: twenty bodies across the bridge to draw twenty dates would be the whole
 *  history.
 */
export type Revision = {
	id: string,
	takenAt: string,
	/**  So a row can say how much a version held without carrying it. */
	characters: number,
};

/**
 *  One seeded note, and which of the seeded folders it lands in.
 * 
 *  An index into the folders the same command creates, which have no id yet. `None` stays
 *  loose, which the first launch shows on purpose.
 */
export type SampleNote = {
	folder?: number | null,
	draft: NoteDraft,
};

/**
 *  No `Title` variant: a note found by its own title needs no excerpt, which would repeat the
 *  biggest thing on the card. That case is `SearchMatch::Title`.
 */
export type SearchField = "tag" | "body" | "item";

/**  What made a note match, and where. */
export type SearchHit = {
	field: SearchField,
	/**  The matching line, not the whole body: a card has room for one. */
	excerpt: string,
};

/**  Three fields rather than a map, so a missing shortcut is a compile error. */
export type ShortcutBindings = {
	capture: string,
	newNote: string,
	palette: string,
};

export type Space = {
	id: string,
	/**  Uniqueness is case-insensitive, decided by persistence. */
	name: string,
	/**  Hoisted to the head of the list, the way a pinned note is on the canvas. */
	pinned?: boolean,
};

export type SpaceDraft = {
	name: string,
};

export type SpanKind = "plain" | "strong" | "code";

export type TagUsage = {
	tag: string,
	noteCount: number,
};

export type TrashedNote = {
	deletedAt: string,
	/**  Derived, never stored: retention can change between versions. */
	purgeAt: string,
} & Note;

/**  Labels cross already translated: the interface language is a front-end preference. */
export type TrayLabels = {
	open: string,
	newNote: string,
	capture: string,
	palette: string,
	quit: string,
};

/**  What the front end renders before it renders anything else. */
export type VaultState = 
/**
 *  A library that has never been encrypted: the first launch asks for a passphrase
 *  twice and creates one.
 */
"absent" | 
/**  A key file is there and the passphrase has not been given yet. */
"locked" | 
/**
 *  Held in Rust, not in the front end: a page reload must not ask again for a library
 *  this process has open.
 */
"unlocked" | 
/**
 *  ⚠️ A database is here and its key file is not. Not `Absent`: a new key over it would
 *  open nothing it holds, and asking for a new phrase would be the first step towards that.
 */
"keyMissing";

/**  Pushed from the preferences panel as it changes, like the tray labels. */
export type WindowBehavior = {
	closeToTray: boolean,
	minimizeToTray: boolean,
};

/**  One zone that moved. A batch of these is what a gesture eventually writes. */
export type ZonePlacement = {
	folderId: string,
	frame: BoardFrame,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

