export const HEADER_GROUPS = [
  'content',
  'caching',
  'range',
  'auth',
  'cookies',
  'security',
  'cors',
  'connection',
  'request',
  'response',
] as const;
export type HeaderGroup = (typeof HEADER_GROUPS)[number];

export type HeaderDirection = 'request' | 'response' | 'both';

export interface HttpHeader {
  /** As it is written on the wire, and what the row copies. A cookie attribute is named alone. */
  readonly name: string;
  readonly group: HeaderGroup;
  readonly direction: HeaderDirection;
  readonly example: string;
  /** The RFC or the living standard that defines it, or « de facto ». */
  readonly by: string;
  readonly security?: true;
  readonly deprecated?: true;
}

export interface HttpHeaderWords {
  /** Keyed by the name in lower case. */
  readonly headers: Readonly<Record<string, string>>;
}

const RFC = 'RFC 9110';
const CACHING = 'RFC 9111';
const COOKIES = 'RFC 6265';
const FETCH = 'Fetch';
const DATE = 'Tue, 06 Oct 2026 18:00:00 GMT';
const ETAG = '"33a64df5"';

export const HTTP_HEADERS: readonly HttpHeader[] = [
  {
    name: 'Content-Type',
    group: 'content',
    direction: 'both',
    example: 'application/json; charset=utf-8',
    by: RFC,
  },
  { name: 'Content-Length', group: 'content', direction: 'both', example: '348', by: RFC },
  { name: 'Content-Encoding', group: 'content', direction: 'both', example: 'br', by: RFC },
  { name: 'Content-Language', group: 'content', direction: 'both', example: 'fr-FR', by: RFC },
  {
    name: 'Content-Disposition',
    group: 'content',
    direction: 'response',
    example: 'attachment; filename="rapport.pdf"',
    by: 'RFC 6266',
  },
  {
    name: 'Content-Location',
    group: 'content',
    direction: 'response',
    example: '/documents/rapport.json',
    by: RFC,
  },
  { name: 'Transfer-Encoding', group: 'content', direction: 'both', example: 'chunked', by: 'RFC 9112' },
  {
    name: 'Accept',
    group: 'content',
    direction: 'request',
    example: 'application/json, text/plain;q=0.9',
    by: RFC,
  },
  { name: 'Accept-Encoding', group: 'content', direction: 'request', example: 'gzip, br, zstd', by: RFC },
  {
    name: 'Accept-Language',
    group: 'content',
    direction: 'request',
    example: 'fr-FR, fr;q=0.9, en;q=0.8',
    by: RFC,
  },
  { name: 'Vary', group: 'content', direction: 'response', example: 'Accept-Encoding', by: RFC },

  {
    name: 'Cache-Control',
    group: 'caching',
    direction: 'both',
    example: 'max-age=3600, public',
    by: CACHING,
  },
  { name: 'Expires', group: 'caching', direction: 'response', example: DATE, by: CACHING },
  { name: 'Age', group: 'caching', direction: 'response', example: '24', by: CACHING },
  { name: 'ETag', group: 'caching', direction: 'response', example: ETAG, by: RFC },
  { name: 'Last-Modified', group: 'caching', direction: 'response', example: DATE, by: RFC },
  { name: 'If-None-Match', group: 'caching', direction: 'request', example: ETAG, by: RFC },
  { name: 'If-Modified-Since', group: 'caching', direction: 'request', example: DATE, by: RFC },
  { name: 'If-Match', group: 'caching', direction: 'request', example: ETAG, by: RFC },
  { name: 'If-Unmodified-Since', group: 'caching', direction: 'request', example: DATE, by: RFC },
  {
    name: 'Pragma',
    group: 'caching',
    direction: 'request',
    example: 'no-cache',
    by: CACHING,
    deprecated: true,
  },

  { name: 'Range', group: 'range', direction: 'request', example: 'bytes=0-1023', by: RFC },
  { name: 'Accept-Ranges', group: 'range', direction: 'response', example: 'bytes', by: RFC },
  { name: 'Content-Range', group: 'range', direction: 'response', example: 'bytes 0-1023/146515', by: RFC },
  { name: 'If-Range', group: 'range', direction: 'request', example: ETAG, by: RFC },

  {
    name: 'Authorization',
    group: 'auth',
    direction: 'request',
    example: 'Bearer eyJhbGciOiJIUzI1NiJ9…',
    by: RFC,
    security: true,
  },
  {
    name: 'WWW-Authenticate',
    group: 'auth',
    direction: 'response',
    example: 'Bearer realm="api", error="invalid_token"',
    by: RFC,
    security: true,
  },
  {
    name: 'Proxy-Authorization',
    group: 'auth',
    direction: 'request',
    example: 'Basic YWxhZGRpbjpvcGVuc2VzYW1l',
    by: RFC,
    security: true,
  },
  {
    name: 'Proxy-Authenticate',
    group: 'auth',
    direction: 'response',
    example: 'Basic realm="proxy"',
    by: RFC,
    security: true,
  },

  {
    name: 'Cookie',
    group: 'cookies',
    direction: 'request',
    example: 'session=38afes7a8; theme=dark',
    by: COOKIES,
    security: true,
  },
  {
    name: 'Set-Cookie',
    group: 'cookies',
    direction: 'response',
    example: 'session=38afes7a8; Secure; HttpOnly; SameSite=Lax',
    by: COOKIES,
    security: true,
  },
  {
    name: 'HttpOnly',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: id=a3fWa; HttpOnly',
    by: COOKIES,
    security: true,
  },
  {
    name: 'Secure',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: id=a3fWa; Secure',
    by: COOKIES,
    security: true,
  },
  {
    name: 'SameSite',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: id=a3fWa; SameSite=Lax',
    by: 'RFC 6265bis',
    security: true,
  },
  {
    name: 'Domain',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: id=a3fWa; Domain=exemple.fr',
    by: COOKIES,
    security: true,
  },
  {
    name: 'Path',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: id=a3fWa; Path=/api',
    by: COOKIES,
  },
  {
    name: 'Max-Age',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: id=a3fWa; Max-Age=3600',
    by: COOKIES,
  },
  {
    name: '__Host-',
    group: 'cookies',
    direction: 'response',
    example: 'Set-Cookie: __Host-id=a3fWa; Secure; Path=/',
    by: 'RFC 6265bis',
    security: true,
  },

  {
    name: 'Strict-Transport-Security',
    group: 'security',
    direction: 'response',
    example: 'max-age=63072000; includeSubDomains; preload',
    by: 'RFC 6797',
    security: true,
  },
  {
    name: 'Content-Security-Policy',
    group: 'security',
    direction: 'response',
    example: "default-src 'self'; img-src 'self' data:",
    by: 'CSP 3',
    security: true,
  },
  {
    name: 'Content-Security-Policy-Report-Only',
    group: 'security',
    direction: 'response',
    example: "default-src 'self'; report-to csp",
    by: 'CSP 3',
    security: true,
  },
  {
    name: 'X-Content-Type-Options',
    group: 'security',
    direction: 'response',
    example: 'nosniff',
    by: FETCH,
    security: true,
  },
  {
    name: 'X-Frame-Options',
    group: 'security',
    direction: 'response',
    example: 'DENY',
    by: 'RFC 7034',
    security: true,
  },
  {
    name: 'Referrer-Policy',
    group: 'security',
    direction: 'response',
    example: 'strict-origin-when-cross-origin',
    by: 'Referrer Policy',
    security: true,
  },
  {
    name: 'Permissions-Policy',
    group: 'security',
    direction: 'response',
    example: 'camera=(), geolocation=(self)',
    by: 'Permissions Policy',
    security: true,
  },
  {
    name: 'Cross-Origin-Opener-Policy',
    group: 'security',
    direction: 'response',
    example: 'same-origin',
    by: 'HTML',
    security: true,
  },
  {
    name: 'Cross-Origin-Embedder-Policy',
    group: 'security',
    direction: 'response',
    example: 'require-corp',
    by: 'HTML',
    security: true,
  },
  {
    name: 'Cross-Origin-Resource-Policy',
    group: 'security',
    direction: 'response',
    example: 'same-site',
    by: FETCH,
    security: true,
  },
  {
    name: 'Clear-Site-Data',
    group: 'security',
    direction: 'response',
    example: '"cache", "cookies", "storage"',
    by: 'Clear Site Data',
    security: true,
  },
  {
    name: 'X-XSS-Protection',
    group: 'security',
    direction: 'response',
    example: '0',
    by: 'de facto',
    security: true,
    deprecated: true,
  },

  {
    name: 'Origin',
    group: 'cors',
    direction: 'request',
    example: 'https://app.exemple.fr',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Allow-Origin',
    group: 'cors',
    direction: 'response',
    example: 'https://app.exemple.fr',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Allow-Credentials',
    group: 'cors',
    direction: 'response',
    example: 'true',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Allow-Methods',
    group: 'cors',
    direction: 'response',
    example: 'GET, POST, PUT, DELETE',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Allow-Headers',
    group: 'cors',
    direction: 'response',
    example: 'Content-Type, Authorization',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Expose-Headers',
    group: 'cors',
    direction: 'response',
    example: 'X-Request-Id',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Max-Age',
    group: 'cors',
    direction: 'response',
    example: '600',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Request-Method',
    group: 'cors',
    direction: 'request',
    example: 'PUT',
    by: FETCH,
    security: true,
  },
  {
    name: 'Access-Control-Request-Headers',
    group: 'cors',
    direction: 'request',
    example: 'content-type, authorization',
    by: FETCH,
    security: true,
  },

  { name: 'Host', group: 'connection', direction: 'request', example: 'api.exemple.fr', by: RFC },
  { name: 'Connection', group: 'connection', direction: 'both', example: 'keep-alive', by: RFC },
  { name: 'Upgrade', group: 'connection', direction: 'both', example: 'websocket', by: RFC },
  { name: 'Via', group: 'connection', direction: 'both', example: '1.1 varnish, 1.1 nginx', by: RFC },
  {
    name: 'Forwarded',
    group: 'connection',
    direction: 'request',
    example: 'for=192.0.2.60;proto=https;host=exemple.fr',
    by: 'RFC 7239',
  },
  {
    name: 'X-Forwarded-For',
    group: 'connection',
    direction: 'request',
    example: '203.0.113.195, 70.41.3.18',
    by: 'de facto',
    security: true,
  },
  { name: 'X-Forwarded-Proto', group: 'connection', direction: 'request', example: 'https', by: 'de facto' },
  {
    name: 'X-Forwarded-Host',
    group: 'connection',
    direction: 'request',
    example: 'exemple.fr',
    by: 'de facto',
  },
  {
    name: 'X-Request-Id',
    group: 'connection',
    direction: 'both',
    example: 'f058ebd6-02f7-4d3f-942e-904344e8cde5',
    by: 'de facto',
  },

  {
    name: 'User-Agent',
    group: 'request',
    direction: 'request',
    example: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    by: RFC,
  },
  {
    name: 'Referer',
    group: 'request',
    direction: 'request',
    example: 'https://exemple.fr/articles/42',
    by: RFC,
  },
  { name: 'Expect', group: 'request', direction: 'request', example: '100-continue', by: RFC },
  {
    name: 'Sec-Fetch-Site',
    group: 'request',
    direction: 'request',
    example: 'cross-site',
    by: 'Fetch Metadata',
    security: true,
  },

  { name: 'Location', group: 'response', direction: 'response', example: '/commandes/42', by: RFC },
  { name: 'Retry-After', group: 'response', direction: 'response', example: '120', by: RFC },
  { name: 'Allow', group: 'response', direction: 'response', example: 'GET, HEAD, PUT', by: RFC },
  { name: 'Date', group: 'response', direction: 'both', example: DATE, by: RFC },
  {
    name: 'Server',
    group: 'response',
    direction: 'response',
    example: 'nginx/1.27.0',
    by: RFC,
    security: true,
  },
  {
    name: 'Link',
    group: 'response',
    direction: 'response',
    example: '</style.css>; rel=preload; as=style',
    by: 'RFC 8288',
  },
  {
    name: 'Alt-Svc',
    group: 'response',
    direction: 'response',
    example: 'h3=":443"; ma=86400',
    by: 'RFC 7838',
  },
  {
    name: 'Server-Timing',
    group: 'response',
    direction: 'response',
    example: 'db;dur=53, app;dur=47.2',
    by: 'Server Timing',
  },
];
